### ISSUE TITLE
Make ANT device configuration more flexbile, e.g. when PM and FE-C are used, have primary power from one and cadence from the other

### ISSUE THREAD

**Issue by robert-budde** [GoldenCheetah/GoldenCheetah#3367] opened 2020-03-06 08:00 UTC
At the moment, if I get the code right, the earlier an ANT device is stated in the GC "profile", the more predecence it will take when supplying the metrics.

While this concept is generally fine when using dedicated (simple/one-metric) sensors such as speed, cadence, heartrate, it is severly limited when using more advanced devices offering multiple metrics such as power meters (offering cadence beside power) or fe-c (offering cadence and power beside controlling the resistance (slope or power).

**Example:**
I have a SRAM Quarq PM (Id 55748) offering cadence WITHIN the power channel. I use a Elite Direto X smart trainer (Id 9997), which inside the fe-c channel also sends power-output and cadence (The Direto also offers a S&C channel). I also use a Polar HRM (Id 9261) - I will leave this out for clarity.

**I am looking for: FE-C for power control and PRIMARY power reading to match these two numbers, Quarq power as secondary (not so critical) BUT Quarq cadence as primary (because it is actually much more reliable and consistent than the Direto estimate).**

using: `9261h, 9997f, 55748p`

The power readings are right, also with AltPower thanks to "setAlt" code at https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/ANT/ANT.cpp#L690-L701 (respecting the order the devices are mentioned in the profile)

But: The cadence will be screwed up because only „SandC“ and pure „Cadence“ channels use setCadence directly; ANT_STANDARD_POWER, ANT_CRANKTORQUE_POWER und FITNESS_EQUIPMENT_TRAINER_SPECIFIC_PAGE use setSecondaryCadence without any "alt" and start overwriting each other with every ANT message coming in because primary cadence is never set: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/ANT/ANT.h#L608-L612

I am aware that an additional cadence sensor (in the first place) would likely fix that, but I think the setup is quite usual and it should work without additional sensors and this also applies to other sensors/setups.

Remark: Implementing "setAlt" for cadence much the same as for power will not suffice as I need the precedence "interleaved".

**Proposal: extend the "f, p and other suffixes in the config with some optional notation to tell how the information on those "aggregate" channels should be ranked**, e.g.

`9261h, 9997f**1p2c**, 55748p**2p1c**` -> use FE-C for primary power and secondary cadence, use PM vice versa.
could be simplified if the code would keep track whether to "fill up":
`9261h, 9997f**2c**, 55748p` -> just telling the FE-C channel to make its cadence secondary (by default, all channels would try to rank each of theirs metrics as high as possible/not already taken).

What do you think?

**Comment by ericchristoffersen** [comment] 2020-03-06 17:24
I at least have an opinion. :)

My non-technical friends already have a horrible time configuring golden cheetah, mostly its with drivers and connectivity but then the selection ui is also difficult for them. The additional capability you're describing here sounds necessary but the concept is way beyond what they'd be willing to engage with.

It could be that the above change is a nice way to implement, but I really think that first the ui needs to be clear.

I think the automatic/implicit ordering hurts usability. Its nice to think that product can automatically do the right thing, but I think better if we can make it clear for customer to choose what they want explicitely.

I think choosing among so many sources deserves an explicit and obvious control window instead of relying on hidden priority heuristics. Something like a set of check boxes for each available device so user can select the streams like a buffet. Key is not letting the user pick impossible combinations (for example multiple sources for the same data.) Could be ui would let the other streams be recorded but not used.

Maybe print a summary at the end showing what data comes from where so user is clear what they will be getting.

Making it clear and easy to select streams from multiple devices seems like a problem that is impossible to overkill.

**Comment by amtriathlon** [comment] 2020-04-02 15:27
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/526

**Closed by amtriathlon** 2020-04-02 15:27 UTC
Labels: duplicate
