### ISSUE TITLE
Chart scale not remmbered

### ISSUE THREAD

**Issue by pavelkroupa** [GoldenCheetah/GoldenCheetah#2600] opened 2017-08-16 19:17 UTC
I always adjust the charts to see Heart rate: 105-180 BPM, and cadence from 65-105.
When I switch to different chart or different activity, I have to re-adjust all scales.Would be nice to add some sort of checkbox to fix the current scale.
Or is there some other work around?
Thanks,
Pavel

**Comment by amtriathlon** [comment] 2019-12-11 12:15
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2044

**Closed by amtriathlon** 2019-12-11 12:15 UTC
Labels: duplicate
