### ISSUE TITLE
3.5_DEV_1901 cann`t open macOS Sierra (10.12) and earlier

### ISSUE THREAD

**Issue by dreaman1003** [GoldenCheetah/GoldenCheetah#3013] opened 2019-02-07 03:12 UTC
macOS Sierra (10.12) and earlier is actually not able to mount the new Apple File System (APFS). 
3.5_DEV1901_MacOS_64bit.dmg is new Apple File System (APFS).

Could you rebuild it for older versions of macOS ?

**Comment by oneilljohn** [comment] 2019-02-07 16:03
This is probably an explanation for and duplicate of issue #3007

**Comment by dreaman1003** [comment] 2019-02-07 16:45
I run in Terminal : shasum -a 256 /Volumes/Data/Down\ Folder/GoldenCheetah_v3.5_DEV1901_MacOS_64bit.dmg

And  the result to show up. 
bab1dcea6beca69adcfc67585efc00aabbed6709890c747cc88110e0de6e62d8

macOS 64Bit SHA-256
bab1dcea6beca69adcfc67585efc00aabbed6709890c747cc88110e0de6e62d8 GoldenCheetah_v3.5_DEV1901_MacOS_64bit.dmg

Nevertheless, it does not mount.
![screen shot 2019-02-08 at 01 39 05](https://user-images.githubusercontent.com/47406893/52427369-2ed49e00-2b43-11e9-9de9-7eb68ca62d4d.jpg)

**Closed** 2019-02-07 16:51 UTC

**Comment by amtriathlon** [comment] 2019-02-07 16:55
Let’s keep the other one, also in the users forum there is a thread specific to report problems affecting this particular build.
