### ISSUE TITLE
Datafilter memory leak

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#4249] opened 2022-07-24 09:17 UTC
Datafilters allocate a lot of memory and are never cleared, fortunately the data they manipulate and create are stored in Result objects that are created and deleted appropriately (generally on the stack).

Some of the more obvious issues:
* clearFilter never gets called in practice, there is no DataFilter::~DataFilter method for a start
* the leaf::clear() method is out of date and does not reflect the multitude of new types of Leaf, nor how the lvalue/rvalue are used/not used
* the runtime object is manipulated by UserMetrics in a spooky action at a distance way (that needs to be addressed)

There is likely a number of other issues hidden in the code- this defect needs to be reviewed in detail.

One example of how to test this:
* add a DataFilter destructor that calls clearFilter
* switch to trends view
* a SEGV will occur since SearchFilterBox::matches allocates a Datafilter on the stack, causing the delete method to be called as it goes out of scope

**Comment by amtriathlon** [comment] 2022-08-29 21:58
There is a reproducible crash in Leaf::clear reported at the forum: https://groups.google.com/g/golden-cheetah-users/c/rYZOMnYeltg/m/kXbtfoH7AgAJ

**Comment by amtriathlon** [comment] 2022-10-20 18:28
I think #4277 (almost) fixes this issue, but I am not sure about the runtime object part.

Recently I've found a crash related to calling clearFilter from DataFilter destructor, it happens when a compound statement has a syntax error, it is easy to reproduce when you edit User Charts trying to add a new method, you start to type the name and GC crashes.

The problem is a DataFilter is created in the stack by DataFilterEdit::checkErrors but, since the parse is incomplete, treeRoot points to a QList<Leaf*> instead to a Leaf* and clearFilter calls Leaf::clear incorrectly.

This can be avoiding setting treeRoot to NULL when there are parsing errors, s.t. the DataFilter constructor does when called with a script, in DataFilter::check and DataFilter::parseFilter, the price is memory will not be released in those cases, but this still is better than never to release it.

I will add this patch to avoid crashes, but ideas to distinguish the cases for properly delete on parsing errors are welcome.

**Closed** 2022-10-22 20:52 UTC
Labels: P0, performance, Expressions & Scripting
