### ISSUE TITLE
[GC 3.5 - Build 1703] [Linux Mint 18.1] Crash when editing or creating custom user metrics

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2399] opened 2017-03-18 18:03 UTC
I often get crashes once a custom user metric is saved. The program crashes during the refresh phase after saving. Below you can see the backtrace using gdb. This particular crash happened when I simply substituted a constant integer value in an existing custom user metric:

> Thread 67282 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff510f7700 (LWP 15787)]
0x00000000014c4978 in std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4 ()
(gdb) bt
#0  0x00000000014c4978 in std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4
    ()
#1  0x0000000000a0346e in UserMetric::~UserMetric() ()
#2  0x0000000000a03749 in UserMetric::~UserMetric() ()
#3  0x000000000061f90e in QHash<QString, QSharedPointer<RideMetric> >::deleteNode2(QHashData::Node*) ()
#4  0x00007fffed69fde9 in QHashData::free_helper(void (*)(QHashData::Node*)) ()
   from /opt/GoldenCheetah/lib/libQt5Core.so.5
#5  0x00000000007634a4 in RideItem::refresh() ()
#6  0x00000000007511b5 in itemRefresh(RideItem*&) ()
#7  0x0000000000756efd in QtConcurrent::MapKernel<RideItem**, QtConcurrent::FunctionWrapper1<void, RideItem*&> >::runIteration(RideItem**, int, void*) ()
#8  0x0000000000756f48 in QtConcurrent::MapKernel<RideItem**, QtConcurrent::FunctionWrapper1<void, RideItem*&> >::runIterations(RideItem**, int, int, void*) ()
#9  0x000000000075736d in QtConcurrent::IterateKernel<RideItem**, void>::threadFunction() ()
#10 0x00007fffee1ae0cd in QtConcurrent::ThreadEngineBase::run() ()
   from /opt/GoldenCheetah/lib/libQt5Concurrent.so.5
#11 0x00007fffed646a43 in ?? () from /opt/GoldenCheetah/lib/libQt5Core.so.5
#12 0x00007fffed64a549 in ?? () from /opt/GoldenCheetah/lib/libQt5Core.so.5
#13 0x00007fffed1156ba in start_thread (arg=0x7fff510f7700)
    at pthread_create.c:333
#14 0x00007fffec5aa82d in clone ()

**Comment by stschake** [comment] 2017-03-18 21:19
The same issue was reported under Windows:

https://groups.google.com/d/msg/golden-cheetah-users/zRamtWe9-Is/RARyMSTQAwAJ

I think the issue is in the refcounting from b9a12c6d60

**Comment by liversedge** [comment] 2017-03-18 21:53
Yes -- I need to put a mutex around it -- its a swine to reproduce reliably.
Can you test out?

Commits 1e1181e64658714206404aeefe15b28f80226fd3 and eb1dc6cf35cc709660ffca6c8542686f211ffc10 should fix it I think.

**Comment by liversedge** [comment] 2017-03-19 14:50
Have tested a fair amount today and have not been able to recreate since this fix was applied, so closing, but need to monitor, since its quite a thorny issue.

**Closed by liversedge** 2017-03-19 14:50 UTC
Labels: crash, metrics error, P0
