### ISSUE TITLE
Select Workout and VideoSync automaticcaly when selecting video

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#4316] opened 2023-01-15 21:10 UTC
In train view when preparing a virtual activity workout:
When a video is selected, select automatically the VideoSync file and the Workout file accordingly (if any)

When no matching file is found (based on exact filename match): do nothing
When user overide this auto-select afterward: accept user choice

**Comment by amtriathlon** [comment] 2023-01-16 17:01
It looks like a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3886

**Closed** 2023-01-16 18:25 UTC

**Comment by vlcvboyer** [comment] 2023-01-20 22:19
#4320
