### ISSUE TITLE
Elite Qubo digital ANT+ support

### ISSUE THREAD

**Issue by ihewitt** [GoldenCheetah/GoldenCheetah#1851] opened 2016-02-16 21:00 UTC
Hi, 
I created a patch adding basic support for the Elite Qubo digital wireless trainer:
https://gist.github.com/ihewitt/6f89405bf3e0d8a216f3

Still a work in progress, but so far it reports the speed and cadence from the device and allows the resistance control to be set from GoldenCheetah train mode.

**Comment by ihewitt** [comment] 2016-02-18 10:14
I've added a gradient mode as well as the power level mode to allow crs workouts, also since there's no ant remote for the qubo, added manual up and down buttons onto the train toolbar..
and added an "underspeed/overspeed" colour highlight since there's a supported speed/power band for the qubo power mode. I'll create a fork for this.

**Comment by ihewitt** [comment] 2016-02-19 23:07
Tracked in pull request #1853

**Comment by liversedge** [comment] 2016-02-19 23:14
cool !

**Comment by xplong666** [comment] 2017-02-25 11:16
super! I'm so excited to see it working in the next release
 
Thanks for your hard work supporting this trainer!

**Comment by liversedge** [comment] 2020-02-01 10:51
the pull request was closed so closing the associated issue.

**Closed by liversedge** 2020-02-01 10:51 UTC
Labels: P1, device support request, training view

**Comment by IdrisTheDragon** [comment] 2020-04-11 19:01
Over the last few days I have wanted to get our elite qubo digital connected to some sort of modern training software. 

### Some general background research on the elite qubo digital:
I found it is supported by elites own myETraining android app, but not thier windows or macOS versions although support is planned apparently. Elite are referring to this device as 'elite qubo digital wireless' in the android app. 

This trainer pre-dates ant+ so doesn't use ant+, it uses what's known as 'ant elite' (https://elitesrl.zendesk.com/hc/en-us/articles/115005339249-Protocols-used-on-Elite-trainers accessed April 2020). So to answer a question from #745 (https://github.com/GoldenCheetah/GoldenCheetah/issues/745) "is it different to the Qubo that is already supported?" which also related to the trainer in this issue: yes it is different from the qubo implementations already supported as they are all ant+ or BLE compatible. There is an option to upgrade firmware (https://elitesrl.zendesk.com/hc/en-us/articles/360011779094-Firmware-Upgrade-Qubo-Digital-Arion-Digital accessed April 2020) but I haven't done this yet, as it requires contacting them (I am waiting for reply) and risking damaging the trainer permanently.

### The Elite Qubo digital and GoldenCheetah
So today I found this work by @ihewitt but am unsure of the final progress on it, it seems to have just faded into the git history.. but I have pulled up his work on the elite qubo digital wireless into a up-to date branch (https://github.com/IdrisTheDragon/GoldenCheetah/tree/elite-qubo-digital-wireless-support). I have got a simple build working (only required dependencies and the optional dependancy libusb) with my elite qubo digital wireless, I could see power reading and speed and cadence. it is currently having issues when there is also a heartrate monitor attached through ant+, it seems to crash the USB ant+ device and I haven't worked out how to get it to log the cause of it yet crash, the usb device just seems to stop responding. I have also tested with a speed&cadence sensor connected, but that seems to work fine and not interfere. I may continue to look at getting this fixed up and submit a pull request in future. 

But for today I am done and I really should be getting on with my major project for uni rather than this, so this was just a quick update on my research and progress into the elite qubo wireless digital...

**Comment by ihewitt** [comment] 2020-04-11 20:04
OK bit of info on this.
After spending some time on this, I was talking to Elite and they made available a firmware upgrade for the Qubo Digital+, which updated the (proprietary) ant+ protocol into a fully FEC compatible protocol making it usable on *any* generic FEC compatible software (at the time it was a rather experimental process)

so 1. my motivation for continuing was rather diminished... but also
2. the firmware upgrade was non-reversible so I had no ability to test or continue with it anyway if I wanted to!

I assumed/expected that the firmware update option and process for these models would be polished and made widely available to anyone requesting it, so really didn't seem worthwhile spending much more time working on this. Although the changes I had made did seem to work just fine for me.
I'll check my local copy and check if I have any additional tweaks and make sure to commit those.
