### ISSUE TITLE
Left/Right pedal balance reversed in February snapshot builds

### ISSUE THREAD

**Issue by AlanBen33** [GoldenCheetah/GoldenCheetah#3819] opened 2021-02-06 22:42 UTC
After the February snapshot builds, the Left/Right pedal balance has become reversed. This was validated by running the January 5th snapshot build and the latest February 5th build concurrently. The same .fit from a Wahoo Elemnt Bolt was imported to one of the GC versions and the Raw Data viewed. The activity was then deleted and the same file was imported into the other version. The Left/Right pedal balance Raw Data is reversed between the two versions. Attached are two screen shots from the same file imported into the two different GC versions.
![GC snapshot build February](https://user-images.githubusercontent.com/78665857/107131142-01da3380-68a2-11eb-8137-9a855c8afad8.jpg)
![GC snapshot build January](https://user-images.githubusercontent.com/78665857/107131146-069ee780-68a2-11eb-9828-b2d6a720204b.jpg)

There is a conversation on Google Groups with the heading "Left/Right pedal balance" where I had a conversation with José Luis García Pallero the who developed the Balance-potencia chart trying to solve the issue.
Thanks
Alan

**Comment by amtriathlon** [comment] 2021-02-06 22:58
Please attach the fit file (zipped) to reproduce the issue.

**Comment by AlanBen33** [comment] 2021-02-06 23:14
Here is the zip file
[2021-01-20-212051-ELEMNT BOLT 90DF-250-0.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5937852/2021-01-20-212051-ELEMNT.BOLT.90DF-250-0.zip)

**Comment by amtriathlon** [comment] 2021-02-14 22:10
There are 2 problems, one in the FIT file and other in our code:
1) The FIT file is incorrect according to specification since it includes the left contribution:
![image](https://user-images.githubusercontent.com/1444784/103826072-e7b7f600-5054-11eb-80da-7e68dc85aec0.png)
in fact if you import it in Garmin Connect left-right balance is not displayed.
2) Our code should detect the situation and mark the data as not available.
This issue was introduced by https://github.com/GoldenCheetah/GoldenCheetah/commit/b29f72d19c5fe0a95ff10da725eae94e061a4338#diff-ec8ebb6b21bbeb8b50ff6e1a352f5917d65316645e22bcb0818e8fee505f4332, the previous version accepted the out-of-spec left contribution.

Obviously it is easy to revert that change, but my concern is we loose the ability to detect LR balance marked as invalid.

**Comment by AlanBen33** [comment] 2021-02-14 22:34
If I understand you correctly, you are saying that there is a standard for data in a FIT file and Wahoo are not following that standard. The Left/Right balance is displayed correctly in the Wahoo Elemnt app, but I guess that means nothing if they are not adhering to the standard.
Not really sure how to go forward with this. I doubt I can get Wahoo to change. I am currently having to copy my Left/Right Balance data in to Excel, make the correction and then copy it back into GC. That is getting tiresome.
It does seem weird that the L/R Torque Effectiveness and the L/R Pedal Smoothness are displayed correctly in GC and it is only the L/R Balance that is swapped in the latest versions.

**Comment by amtriathlon** [comment] 2021-02-14 23:09
> If I understand you correctly, you are saying that there is a standard for data in a FIT file and Wahoo are not following that standard. The Left/Right balance is displayed correctly in the Wahoo Elemnt app, but I guess that means nothing if they are not adhering to the standard.

Exactly, you can verify this importing the file to Garmin Connect for example.

> Not really sure how to go forward with this. I doubt I can get Wahoo to change. I am currently having to copy my Left/Right Balance data in to Excel, make the correction and then copy it back into GC. That is getting tiresome.

If we fix the pending issue it would be worse, no L/R balance data would be imported.

> It does seem weird that the L/R Torque Effectiveness and the L/R Pedal Smoothness are displayed correctly in GC and it is only the L/R Balance that is swapped in the latest versions.

Yes, L/R Torque Effectiveness and the L/R Pedal Smoothness are Ok, only L/R Balance is out of spec.

**Comment by AlanBen33** [comment] 2021-02-14 23:15
I am not sure that I have enough information or knowledge regarding the FIT file format and specification to make a good argument to Wahoo. How do you think I should proceed?

**Comment by amtriathlon** [comment] 2021-02-14 23:33
> I am not sure that I have enough information or knowledge regarding the FIT file format and specification to make a good argument to Wahoo. How do you think I should proceed?

I think the fact L/R Balance is not displayed when the FIT file is imported to Garmin Connect should be enough to report the issue, you can try that by yourself without the need to know anything about the FIT file format.

**Closed** 2021-02-15 13:41 UTC
Labels: P3, bug, file format error

**Comment by iforpowell** [comment] 2021-06-19 17:14
OK If I am reading this correctly you are not accepting LR power balance data if the top bit is not set to indicate Right.  I believe the data is perfectly valid with this bit not set.  You just don't know if it's left or if it's right.  I can see that this is annoying but I don't see it as not being allowed in the FIT SDK.  I have an Android app IpBike where a user has complained about this issue.  I just pass though this bit based on what the power meter is giving the app.  I need to check what the power meter is but I strongly suspect it's not giving the left right indication which is why I am not putting it in the .FIT file.

**Comment by amtriathlon** [comment] 2021-06-19 20:26
> OK If I am reading this correctly you are not accepting LR power balance data if the top bit is not set to indicate Right.

Right 

>I believe the data is perfectly valid with this bit not set. You just don't know if it's left or if it's right. I can see that this is annoying but I don't see it as not being allowed in the FIT SDK.

It says “unknown”, we represent this as NA, and Garmin Connect seems to be doing the same.
Considering Garmin controls the ANT+ spec, I tend to consider it a kind of reference implementation.

> I have an Android app IpBike where a user has complained about this issue. I just pass though this bit based on what the power meter is giving the app. I need to check what the power meter is but I strongly suspect it's not giving the left right indication which is why I am not putting it in the .FIT file.

You can try uploading the files your App generates to Garmin Connect for testing independent of GoldenCheetah.

**Comment by mjunkmyjunk** [comment] 2022-01-04 01:45
Just wanted to share that Karoo is also one of the culprits to NOT adhering to the FIT file specs for LR balance.
FIT file imported to GC and GoldenCheetah yielded no LR Balance data. 

You can refer to this thread for more details if needed:
 https://forum.intervals.icu/t/difference-in-left-right-balance/3627/20
