### ISSUE TITLE
Not importing other Cycling Dynamics data from FIT file when no Platform Center Offset data available

### ISSUE THREAD

**Issue by tjeerd-tx** [GoldenCheetah/GoldenCheetah#3619] opened 2020-10-01 10:15 UTC
When importing FIT files without PCO (Platform Center Offset), but with PP (Power Phase) or PPP (Peak Power Phase) data, the PP and PPP data are not imported.

FIT file does contain PP and PPP data:
![image](https://user-images.githubusercontent.com/61319032/94796489-29465e80-03df-11eb-98b9-71d9f097e7f4.png)

GoldenCheetah does not import PP and PPP data:
![image](https://user-images.githubusercontent.com/61319032/94796592-4844f080-03df-11eb-9e89-e1793cfa4ea3.png)

FIT file, csv converted file from FIT and activity JSON file from GoldenCheetah:
[GC no PP or PPP without PCO.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5311137/GC.no.PP.or.PPP.without.PCO.zip)

**Comment by amtriathlon** [comment] 2020-10-01 15:05
These fields (69-70-71-72 according to spec.) are imported when present in record messages, independent of other fields:
https://github.com/GoldenCheetah/GoldenCheetah/blob/8c30a6da4a200d5b8d371898da8c25dffa2a0633/src/FileIO/FitRideFile.cpp#L1871
likely there are other issues involved, not just the absence of Platform Center Offset data.

**Comment by tjeerd-tx** [comment] 2020-10-02 15:52
Found out that PPP is displayed correctly in Garmin Connect for this file:
![image](https://user-images.githubusercontent.com/61319032/94943376-e7e5aa00-04d7-11eb-802a-6eb6282762c4.png)

**Comment by amtriathlon** [comment] 2020-10-02 15:57
Yes, I have seen that and marked it as a file format error.

What I am saying is the absence of PCO doesn't seem to be the cause, if I enable debugging in GC FIT importer the fields 69-72 are not detected by our code.

**Comment by tjeerd-tx** [comment] 2020-10-02 16:06
What specification are the field numbers 69-70-71-72 from?

**Comment by amtriathlon** [comment] 2020-10-02 17:05
https://www.thisisant.com/developer/

**Closed** 2020-10-04 21:06 UTC
Labels: P3, file format error
