### ISSUE TITLE
Port to Qt6

### ISSUE THREAD

**Issue by andreasbuhr** [GoldenCheetah/GoldenCheetah#3983] opened 2021-07-26 16:01 UTC
Hi, I just wanted to let you know about the current state of my efforts to build with Qt 6.2 (dev branch)

With all the changes in the pull requests I created, I just compiled and linked GoldenCheetah successfully with Qt 6.2. No testing has been done so far on any of the pull requests I created.

Next would be testing, modifying the patches to work with both Qt5 and Qt6, and sorting out some remaining issues. Most of the pull requests I created a very low risk, I assume. But some need more testing, most prominently the Qwt upgrade https://github.com/GoldenCheetah/GoldenCheetah/pull/3956 and the QRegExp->QRegularExpression transition https://github.com/GoldenCheetah/GoldenCheetah/pull/3960 .
Unfortunately, I will run out of time allocated for this project soon and won't be able to finish it. I'll have to stop working on GoldenCheetah and the open pull requests.

Anyway, I hope that the sequence of pull request generated will be of value to you and I will be around if you have any questions.

**Comment by liversedge** [comment] 2021-07-28 09:38
Did your GC 6.2QT build actually startup ?

**Comment by andreasbuhr** [comment] 2021-07-28 09:40
Yes, it started. It loaded the stored activities. It segfaulted after a few clicks.

**Comment by amtriathlon** [comment] 2024-01-13 20:33
All Qt6 Refactor PRs are merged and master can be build using Qt 6.2.4 (without R/Python for now):

![image](https://github.com/GoldenCheetah/GoldenCheetah/assets/1444784/3cad5fcd-657a-45ab-8231-7ee52bba06c3)

We can start testing!

PS: [thank you very much, Adreas](https://github.com/GoldenCheetah/GoldenCheetah/commit/1fb92d1bf5cdf68ae6783cf7a5b0eb978416e5a1)!

**Comment by liversedge** [comment] 2024-01-13 21:03
Thank you Ale and so good to see Andreas’ work finally committed.
Will look at python integration. Now might be the time to drop R support?

**Comment by liversedge** [comment] 2024-01-13 21:04
Also need to get Andreas on the about box contributors list- this was a fantastic effort !

**Comment by amtriathlon** [comment] 2024-01-13 21:15
I added Andreas to About Box in https://github.com/GoldenCheetah/GoldenCheetah/commit/1fb92d1bf5cdf68ae6783cf7a5b0eb978416e5a1
It looks like R/Python issues are similar to the ones fixed by Andreas, I think we can fix them following the same pattern, not sure about KML since it uses Boost, perhaps we could drop it.

**Comment by liversedge** [comment] 2024-01-13 22:53
KML is dropped on Windows already I think?
Anyway I think it can be dropped, maybe we clean out in 3.7 since there are lots of features almost no one uses

**Comment by amtriathlon** [comment] 2024-01-15 13:24
> KML is dropped on Windows already I think?

In official builds is dropped for macOS and no one has ever complained, it is included for Windows and Linux builds, but I don't know if it is used.

> Anyway I think it can be dropped, maybe we clean out in 3.7 since there are lots of features almost no one uses

Agree, for now I will exclude it from my builds.

**Comment by amtriathlon** [comment] 2024-01-15 13:57
I continued testing my Windows build using Qt 6.2.4 and it is working pretty well. Except for R/Python which I am planning to review later, all remaining charts in all 3 views are working and they look nice and responsive, even overlay widgets over VLC video is working to my surprise.
 @andreasbuhr do you have any recommendation about what QT6 version we should target?

**Comment by andreasbuhr** [comment] 2024-01-15 14:28
> @andreasbuhr do you have any recommendation about what QT6 version we should target?

No sorry. I changed jobs in January 2023 and I am not that deep in Qt any more.

**Comment by amtriathlon** [comment] 2024-01-15 21:26
Python charts are running on Qt 6.2.4 after replacing QRegExp by QRegularExpression in https://github.com/GoldenCheetah/GoldenCheetah/commit/1f999a3957ed9e861c46a0bb3490d5c1c0dfc066

**Comment by liversedge** [comment] 2024-01-16 09:01
Nice one, was worried this was going to be much harder !

@andreasbuhr congratulations on your new job - albeit a year late :)

**Comment by amtriathlon** [comment] 2024-01-16 14:02
**Update:** R Charts are also working when building master with Qt 6.2.4

**Comment by amtriathlon** [comment] 2024-01-16 18:08
Update: CloudDB client code in master is adapted to Qt 6 too

**Comment by amtriathlon** [comment] 2024-01-16 19:50
> KML is dropped on Windows already I think?

In official builds KML is dropped on macOS, on Windows a libkml and Boost version from https://github.com/GoldenCheetah/WindowsSDK are being used, these were built by @Joern-R long time ago, IIRC.

> Anyway I think it can be dropped, maybe we clean out in 3.7 since there are lots of features almost no one uses

For now I am dropping it from my Windows builds, I will give it another try when I start building on Linux.

**Comment by Joern-R** [comment] 2024-01-17 07:17
Agree to drop it. Not sure if anybody uses this feature at all. With the
port to QT6 I also suggest to put the "WindowsSDK" to status "deprecated".

Am Di., 16. Jan. 2024 um 20:51 Uhr schrieb Alejandro Martinez <
***@***.***>:

**Comment by liversedge** [comment] 2024-01-17 11:08
> **Update**: Python charts are working when building with Qt 6.2.4 after replacing QRegExp by QRegularExpression in [1f999a3](https://github.com/GoldenCheetah/GoldenCheetah/commit/1f999a3957ed9e861c46a0bb3490d5c1c0dfc066) and [8e2eb3f](https://github.com/GoldenCheetah/GoldenCheetah/commit/8e2eb3fc1894ba853dbed46f11fbad83187f95d9)

I think the signals are not connected, so no output occurs?

> [11:02:19.724] warning: QObject::connect: No such slot GenericChart::addCurve(QString,QVector<double>,QVector<double>,QStringList,QString,QString,QStringList,QStringList,int,int,int,QString,int,bool,bool,bool,bool) in ../src/Charts/PythonChart.cpp:465 (unknown:0)
> [11:02:19.963] warning: QObject::connect: No such slot GenericChart::addCurve(QString,QVector<double>,QVector<double>,QStringList,QString,QString,QStringList,QStringList,int,int,int,QString,int,bool,bool,bool,bool) in ../src/Charts/PythonChart.cpp:465 (unknown:0)

**Comment by amtriathlon** [comment] 2024-01-17 12:28
> Agree to drop it. Not sure if anybody uses this feature at all.

May be we can ask in users forum (?)

> With the port to QT6 I also suggest to put the "WindowsSDK" to status "deprecated".

For now we are using some components in AppVeyor builds, since the ABI has not change they still useful.

**Comment by amtriathlon** [comment] 2024-01-17 12:32
> > **Update**: Python charts are working when building with Qt 6.2.4 after replacing QRegExp by QRegularExpression in [1f999a3](https://github.com/GoldenCheetah/GoldenCheetah/commit/1f999a3957ed9e861c46a0bb3490d5c1c0dfc066) and [8e2eb3f](https://github.com/GoldenCheetah/GoldenCheetah/commit/8e2eb3fc1894ba853dbed46f11fbad83187f95d9)
> 
> I think the signals are not connected, so no output occurs?
> 
> > [11:02:19.724] warning: QObject::connect: No such slot GenericChart::addCurve(QString,QVector,QVector,QStringList,QString,QString,QStringList,QStringList,int,int,int,QString,int,bool,bool,bool,bool) in ../src/Charts/PythonChart.cpp:465 (unknown:0)
> > [11:02:19.963] warning: QObject::connect: No such slot GenericChart::addCurve(QString,QVector,QVector,QStringList,QString,QString,QStringList,QStringList,int,int,int,QString,int,bool,bool,bool,bool) in ../src/Charts/PythonChart.cpp:465 (unknown:0)

Yes, I should had qualified that affirmation, neither of R/Python charts I use and tested use GC Charts...

**Comment by amtriathlon** [comment] 2024-01-18 14:48
> I think the signals are not connected, so no output occurs?
> 
> > [11:02:19.724] warning: QObject::connect: No such slot GenericChart::addCurve(QString,QVector,QVector,QStringList,QString,QString,QStringList,QStringList,int,int,int,QString,int,bool,bool,bool,bool) in ../src/Charts/PythonChart.cpp:465 (unknown:0)

The problem was caused by https://github.com/GoldenCheetah/GoldenCheetah/commit/466bdf19397addda4e263d8dd506061392f31ff1, after reverting it Python Charts work with GC Charts when building with Qt6

**Comment by amtriathlon** [comment] 2024-01-18 22:52
Update: 2 crashes due to dereferencing the end() iterator were fixed (https://github.com/GoldenCheetah/GoldenCheetah/commit/bf28d7398ce224051a0538407f39d913b9eba15d and https://github.com/GoldenCheetah/GoldenCheetah/commit/573967fe47164855a6defbe7f157fc3a15a18b8a), while these go silent on Qt5 they crash on Qt6.

**Comment by amtriathlon** [comment] 2024-01-18 22:52
Main pending issue now is Metric Trends chart not being correctly restored, they work initially and after View > Reset Layout / Charts > Reset to default, but they become blank after GoldenCheetah restart, ideas are welcome.

**Comment by amtriathlon** [comment] 2024-01-19 18:43
A crash on Trends KPI chart was reported at the forum: https://groups.google.com/g/golden-cheetah-users/c/31h89MspzeA/m/qZ6jBNgiAwAJ due to indexing an empty list, I can reproduce it on Linux but not on Windows, the weird part is the preceding line is intended to make sure the list is not empty:

https://github.com/GoldenCheetah/GoldenCheetah/blob/573967fe47164855a6defbe7f157fc3a15a18b8a/src/Core/DataFilter.cpp#L4475-L4480

**Comment by jlaunay** [comment] 2024-01-23 00:50
Thanks a lot for your work, master also builds with Qt 6.6.1 on archlinux (same problem with the Metric Trends chart).
QT_QPA_PLATFORM=wayland is now supported with the Qt 6 build and it runs perfectly on Sway.

![image](https://github.com/GoldenCheetah/GoldenCheetah/assets/1137028/fa7dc368-b051-4e4c-85ce-2e7516fb9df4)

**Comment by amtriathlon** [comment] 2024-01-23 23:13
> Main pending issue for me now when building with Qt6 is Metric Trends chart not being correctly saved.

Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/4224fd193cb425ce2a4d0b23ff6e8e06b95193b1, solution was trivial, to find the cause, not so much :(

**Comment by lennartalff** [comment] 2024-10-08 01:49
Similar to @jlaunay I'm working with the current master branch on Arch Linux with QT 6.7.3 and also with `QT_QPA_PLATFORM=wayland`.

The Workout Editor does not seem to update/replot properly. Only resizing the GC window are deselecting and reselecting it makes the workout editor update. If I run GC with `QT_QPA_PLATFORM=xcb` though, everything works as expected. 
The some goes for the telemtry widgets (power, elapsed time, etc.) during a record, they update only while resizing the window.

If I set `QT_QUICK_BACKEND=software` the behaviour changes slightly. In that case the workout editor does not update/replot if I change the workout selection in the sidebar but it updates if I hover over the workout editor area with the cursor and the workout blocks are highlighted accordingly. Downside are some weird rendering artefacts.

Can anyone reproduce this problem with wayland?

**Closed** 2024-12-04 07:54 UTC
Labels: QT6 Refactor
