### ISSUE TITLE
sml files getting cutoff

### ISSUE THREAD

**Issue by kpjoubert** [GoldenCheetah/GoldenCheetah#2495] opened 2017-04-29 23:18 UTC
When importing the two attached sml files I seen to get an error.

After import using "activity: import from file" goldencheetah only displays the first 18 minutes of the workout 4-27 workout, and does something similar for the 4-26 file.

I checked the .json file and it inserted a "nan" for cadence value at 18:47, and inf for the kph value; that is where it cuts off.

Viewing the original .sml file _ I don't see anything special at those time points that might cause the translator to throw the error.

I fixed the .json file to take out the nan and inf and everything works fine.

[corrupted data files.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/966465/corrupted.data.files.zip)

**Comment by amtriathlon** [comment] 2017-05-09 22:25
Hi Kevin, which version are you using?
I think this is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2198, which was fixed for v3.5.
I can't reproduce the problem using the last development build: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1705X

**Closed by amtriathlon** 2017-05-09 22:25 UTC
Labels: duplicate, Fixed already
