### ISSUE TITLE
[GC 3.5 - Build 1703] [Linux Mint 18.1] Crash when changing a metric in an existing chart

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2401] opened 2017-03-18 18:04 UTC
I often get crashes when editing charts in the Trends view. Crashes occur on charts in the sidebar, as well as in the top bar. Below you can see the backtrace using gdb. This particular crash happened in an existing chart where I substituted one regular metric with another.

> Thread 1 "GoldenCheetah" received signal SIGSEGV, Segmentation fault.
0x0000000000628726 in LTMPlot::createMetricData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
(gdb) bt
#0  0x0000000000628726 in LTMPlot::createMetricData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
#1  0x000000000062f306 in LTMPlot::createCurveData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
#2  0x0000000000630e61 in LTMPlot::setData(LTMSettings*) ()
#3  0x0000000000663dd8 in LTMWindow::refreshStackPlots() ()
#4  0x00000000006674e8 in LTMWindow::refreshPlot() ()
#5  0x0000000000667aa0 in LTMWindow::refresh() ()
#6  0x0000000000ac67ad in LTMWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#7  0x00007fffed83b3e1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/GoldenCheetah/lib/libQt5Core.so.5
#8  0x000000000065fe40 in LTMTool::editMetric() ()
#9  0x0000000000ac5e4d in LTMTool::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00007fffed83b3e1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/GoldenCheetah/lib/libQt5Core.so.5
#11 0x00007ffff58ae822 in QAbstractButton::clicked(bool) ()
   from /opt/GoldenCheetah/lib/libQt5Widgets.so.5
#12 0x00007ffff58aea14 in ?? () from /opt/GoldenCheetah/lib/libQt5Widgets.so.5
#13 0x00007ffff58b05b7 in ?? () from /opt/GoldenCheetah/lib/libQt5Widgets.so.5
#14 0x00007ffff58b070c in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /opt/GoldenCheetah/lib/libQt5Widgets.so.5

**Comment by liversedge** [comment] 2017-03-18 19:37
I think this may be a duplicate of #2400, so gonna close it.
Will reopen if fixing #2400 doesn't fix this one.

**Comment by liversedge** [comment] 2017-03-18 21:26
I think I can recreate this, but fixed it temporarily in this commit f346611390bcba8ee4e37a135aa24def4b10db90 can you check and report back?

**Closed** 2017-03-19 14:49 UTC
Labels: charting error, configuration, crash
