### ISSUE TITLE
L/R Balance Chart display of 0 when other values present

### ISSUE THREAD

**Issue by ph4r** [GoldenCheetah/GoldenCheetah#3888] opened 2021-05-13 11:11 UTC
On Ride Page, Graph for L/R Balance shows 0 values as 50 instead of 0 when L/R Balance is populated.  I do some single-leg drills, and while I can clearly see the values from Left Leg (It goes to 100), the right leg is hard to see as it is drawn as 50 instead of 0 as in the file.  In my case, Power is still present, and TE shows close to 100 for the Right Side when this happens and Right PS was present as well.
![image](https://user-images.githubusercontent.com/23483137/118117989-481bc300-b3ba-11eb-81af-af9488f8fe65.png)
![image](https://user-images.githubusercontent.com/23483137/118118031-5bc72980-b3ba-11eb-8979-4fd4167039bf.png)
![image](https://user-images.githubusercontent.com/23483137/118118099-76010780-b3ba-11eb-8f30-b08f9eb26ec2.png)

**Comment by amtriathlon** [comment] 2021-05-13 11:56
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3473

**Closed by amtriathlon** 2021-05-13 11:56 UTC
