### ISSUE TITLE
Garmin fenix 6X alitude and speeed are missing

### ISSUE THREAD

**Issue by kdelios** [GoldenCheetah/GoldenCheetah#3168] opened 2019-09-20 11:16 UTC
Hello,

In the past I was using a Garmin fenix 5X with stryd, no problems at all.
Now I have upgraded to a Garmin fenix 6X (with stryd).
With the fenix 6X altitude and speed data are gone.
Of course, elevation & speed existing into fit file, because they appear at stryd's PowerCenter (Garmin feeds the fit file there).
I have attached the fit file.
Thank you.

[4077461142.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3635616/4077461142.zip)

**Comment by amtriathlon** [comment] 2019-09-20 12:47
It looks like a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3161

**Closed by amtriathlon** 2019-09-20 12:47 UTC
Labels: duplicate
