### ISSUE TITLE
Elite Fluid Elastogel (Round Unit)

### ISSUE THREAD

**Issue by darbsp** [GoldenCheetah/GoldenCheetah#3177] opened 2019-10-04 15:15 UTC
![image](https://user-images.githubusercontent.com/14996848/66218894-09903380-e6c2-11e9-9dad-b646f678d0ce.png)

Would there be any chance of adding this as a new trainer?

Thanks,

**Comment by Ramoonus** [comment] 2019-10-07 15:48
what do you mean with round unit?

**Comment by darbsp** [comment] 2019-10-08 18:22
I presume it is something to do with the resistance block. It was just the name of the trainer on http://www.powercurvesensor.com/cycling-trainer-power-curves/

**Comment by amtriathlon** [comment] 2019-10-27 00:07
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2720

**Closed by amtriathlon** 2019-10-27 00:07 UTC
Labels: duplicate
