### ISSUE TITLE
Import Wizard changes time when you change date

### ISSUE THREAD

**Issue by mtbkeith** [GoldenCheetah/GoldenCheetah#2666] opened 2017-10-24 07:11 UTC
When you use the import wizard, you can change the date for any selected row(s). 

The way the code is written the time is also changed which I think is unexpected behavior; it looks at the current time and subtracts the duration. If you have a 2hr activity and perform the import at 1am. Select "Today" and you'll end up with a time in the future. Personally, I would suspect that most devices may have the right time but had the wrong date. So I do not believe the time should be adjusted. 

At a minimum, all choices other than today also adjust the time incorrectly. The test for rstart should be < 0 and should not include zero. 
```
if (rstart <= 0) {
```

I can work on a change, just would like 

some input. 

File: RideImportWizard.cpp
Method: RideImportWizard::todayClicked(int index)

<img width="919" alt="grab-import-time-is-changed" src="https://user-images.githubusercontent.com/9326275/31929180-2b800258-b858-11e7-8b94-e0a548b1decb.png">

**Comment by liversedge** [comment] 2017-10-25 09:01
It shouldn't set the time to the future, it should set the time to timenow - rideduration.

That was the original intent, since typically if the date is incorrect, everything is.

Most users don't set the date but not the time ?

**Comment by liversedge** [comment] 2018-04-14 12:28
this is intended behaviour so closing.

**Closed by liversedge** 2018-04-14 12:28 UTC
Labels: P2
