### ISSUE TITLE
[Old 70] Training Plan Manager 

### ISSUE THREAD

**Issue by grauser** [GoldenCheetah/GoldenCheetah#266] opened 2012-11-10 09:12 UTC
Added by Julian Baumgartner over 2 years ago. Updated about 1 year ago.
Description
--
Hello all,

A while ago I contacted Mark Liversedge who in turn contacted Damien Grauser about an idea I had to create a feature that would allow a user to build daily workouts using Keisuke's Training Menu Generator plugin, have the BikeScore, IF, and Kj calculated based on the created workout, have these workouts saved as part of a larger plan and then plot those workouts in a "Predicted PMC" The basic idea would be that a user could create a few weeks/months of workouts with a specific event/race in mind and see on a PMC how their form would progress; something to follow. They could then compare the "Predicted PMC" based on the future workouts with what they actually did in their downloaded workouts on the PMC and make adjustments to their future workout plans accordingly... Further, if the user has a Garmin Edge 705 or 500 (or even PT Joule?), they could transfer the workouts to the device...

Mark thought this was a pretty neat idea though I'd imagine that he's got his hands full with the Metadata feature... I reached out to him as I saw this idea as somewhat of an extension of the work he's done with the metadata and figured he might be the best one to help see it to fruition...

I've been using this method of planning (and monitoring) my training for several years with an Excel workbook and have most of my teammates do as well... It's proven to be very successful and all but eliminated our need to pay a coach as we can save the training plans and reuse them, share them etc... It has put control of our training back into our hands.

It's my opinion that this type of feature is the next thing in cycling software and I would love to see GC lead the way...

I'm more than willing to aide in any way I can though as mentioned my ability to actually code C++ is limited so I may just be a great cheerleader... :)

I'm not sure how much work this is or what the best way of implementing it is, but I feel strongly about its potential- so much so that I've ordered a C++ book and am now mumbling classes and objects in my sleep! (I'll learn this code gosh darnit!)

-Julian

History
--
* 1) Updated by Julian Baumgartner about 2 years ago
Patch Attached set to No
 
Thread about this idea here: http://groups.google.com/group/golden-cheetah-users/browse_thread/thread/94d205597298e223

Links to sketches of this idea and the Excel workbook:

Workbook: http://dl.dropbox.com/u/6564666/Training4.xls
Sketches: http://dl.dropbox.com/u/6564666/1.jpg
http://dl.dropbox.com/u/6564666/2.jpg

--
* 2) Updated by Mark Liversedge over 1 year ago
Target version set to 3.1
 
Training Planning is the #1 feature for v3.1

--
* 3) Updated by Mark Liversedge about 1 year ago
 
Some random thoughts (also see PB feature request 454).

1. Athlete profile
what are the bests from history and targets for metrics like 1hr power, 15s power etc
when can I train, what sort of training is best by day (turbo/run/road etc)
2. Season(s)
when does it start/end
what are the Season races/events and associated goals
3. "Periodisation" / Cycles
date range
basic planning parameters - e.g. Train/Rest 4+1 weeks, 1d per week etc, by Stress Balance/RAMP
targets - what am i looking to develop in each cycle - track against season goals / events
Generate target loads & training mix by week/month/cycle
allow user to tweak graphically.
4. Activity Plan
Planned activities - (linked to workout library)
look at PM for future, tweak/adjust graphically
Autosolve for target LTS, stress balance
Manage against cycles (above) if they are defined, otherwise freeform/adhoc.
5. Workout Library
Workout definitions
Build from past activities
Define in generic format and create Garmin workouts, Computrainer .ergs etc
DELIVER A PREBUILT LIBRARY OF USER CONTRIBUTED WORKOUTS

**Comment by liversedge** [comment] 2015-07-24 17:06
Closed as dupe of #515 but referenced the nots in there.

**Closed by liversedge** 2015-07-24 17:06 UTC
Labels: diary view, feature request, function request, P1
