### ISSUE TITLE
Qt5.15 and higher deadlock between QGraphicsScene and QtConcurrent

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#3611] opened 2020-09-19 06:22 UTC
Since Qt5.15 there is a deadlock when accessing the global thread pool. 

This is most noticeable at startup and when metrics are refreshed. The metric refresh uses QtConcurrent::map() which "hogs" all the threads in the global threadpool, this causes a deadlock in the gui where charts that use QGraphicsScene (Overview, AthleteView and UserChart, GenericPlot etc) all block waiting for a free thread.

We need to ensure there are enough threads free for the gui components when refreshing metrics-- this may mean dropping QtConcurrent::map and using QThread instead, and possibly reduce overall performance of metric refresh, but increase overall responsiveness in the application.

**Comment by ericchristoffersen** [comment] 2020-09-20 18:03
Would it work to init qtconcurrent with a private threadpool? That way os can still share work between all outstanding threads and everyone can make progress.

**Comment by liversedge** [comment] 2020-09-21 09:18
possibly, but will mean using another approach since QtConcurrent::map() uses the global thread pool and cannot be changed (nor the priority). It may be ok to use a QRunnable and queue against a private thread pool, or maybe just chunk up to worker threads we manage.

**Comment by ericchristoffersen** [comment] 2020-09-22 01:21
So lame! Probably the reason is horrible, but not very polite. Replace map with your own that takes private threadpool.

**Comment by amtriathlon** [comment] 2020-09-22 20:56
Currently this affects only macOS builds, Windows and Linux are still on Qt 5.14.2, there are 2 relatively straightforward options to go back on Travis until this is resolved:
1. Qt 5.13.2 is included in xcode 10.1 image running on macOS 10.13
2. Qt 5.14.1 is included in xcode 11.3 image running on macOS 10.14

Let me know if you want to generate a snapshot with one of this options.

**Comment by liversedge** [comment] 2020-09-23 06:21
I think that would be a smart move temporarily, as I only noticed myself when launching on MacOS and thought it had crashed.
I will fix this tho.

**Comment by amtriathlon** [comment] 2020-09-23 22:57
Snapshot build with Qt 5.14.1 on macOS 10.14 is available for download, but I have not tested it, yet.

**Comment by ericchristoffersen** [comment] 2020-09-25 01:41
> Currently this affects only macOS builds, Windows and Linux are still on Qt 5.14.2, there are 2 relatively straightforward options to go back on Travis until this is resolved:
> 
> 1. Qt 5.13.2 is included in xcode 10.1 image running on macOS 10.13
> 2. Qt 5.14.1 is included in xcode 11.3 image running on macOS 10.14
> 
> Let me know if you want to generate a snapshot with one of this options.

Does anyone know why this deadlock is only present with qt 5.15? Do we think this is a qt bug? I poked around qt forums and didn't find a mention, ditto for the docs.

**Comment by liversedge** [comment] 2020-09-25 07:03
I'm building with 15.1 on Linux and still see the deadlock issue.

**Comment by DRiKE** [comment] 2020-09-28 10:02
Perhaps this is a different bug, but before I create separate ticket:
On linux (using qt 5.15.1, v3.6-DEV2009) the Athletes page is never drawn, and the Overview tab on the Activities page is neither. However, when I switch from the Overview tab to the summary tab, I briefly see a glimpse of what should be there on the Overview tab. Similarly, when I click on the Athletes page (and nothing gets rendered, so I still see the previous page) and then I close GoldenCheetah, I briefly see something appearing as well.

Are these caused by this same bug?

**Comment by liversedge** [comment] 2021-06-12 09:12
will put in a workaround for 3.6, in 3.7 we can move to Qt6 and a private threadpool.

**Comment by amtriathlon** [comment] 2021-06-25 21:59
Do we really need to upgrade to Qt 5.15 for v3.6 release?

**Comment by liversedge** [comment] 2021-06-26 08:44
No. The rendering issue described is related to opengl drivers not qt. I have experimented with most of the qt releases and its clear that the qtconcurrent thread pooling approach is broken- we need to define our own private threadpool to resolve this deadlock.

For release it may be better to remove the use of qtconcurrent and manage threads in the ridecache. Qt 6.2 will arrive at the end of the year and we can put a longer term solution in place then (and update to qt6 which will take a lot of work).

**Comment by liversedge** [comment] 2021-07-10 06:28
I notice that the official builds use qt 5.14.1 and on MacOS this issue is not present, it is present on Linux with Qt 5.14 and 5.15 (I build my developer builds there). @amtriathlon do you know if this happens with the official windows builds and Qt 5.14.1 ?

I'm wondering if it is a Linux only issue?

**Comment by amtriathlon** [comment] 2021-07-10 09:02
Yes Mark, it doesn’t happen on Windows or macOS with 5.14, that’s the reason I changed back from 5.15 in https://github.com/GoldenCheetah/GoldenCheetah/commit/5fdf427f391f9ac877b01968daa81fbd93d5f2cd, and recently asked to defer this to 3.7, since it isn’t an issue with official builds.

I currently don’t have my Linux box available to confirm, but it neither was an issue on Linux using 5.14, IIRC. You can check with the Travis generated AppImage.

**Comment by liversedge** [comment] 2021-07-10 12:54
Excellent, lets shift this to the 3.7 queue then. I build with latest everything which is probably not such a great idea !!

**Comment by andreasbuhr** [comment] 2021-07-16 13:16
Is there a bugentry on bugreports.qt.io for this? I'd like to make sure this is fixed in Qt 6.2, which we are currently testing.

**Comment by liversedge** [comment] 2021-07-16 13:39
Strictly speaking it is not a bug-- its just that qtconcurrent uses the system thread pool which leaves none available for anything else. In Qt 6.2 you can create a private thread pool and use it with qtconcurrent and avoid the issue reported here.

See the qt docs:
https://doc.qt.io/qt-6/qtconcurrentrun.html

**Comment by amtriathlon** [comment] 2022-06-09 13:40
Regrettably Qt5.14.2 is no longer available on AppVeyor Windows images, I switched ci-builds to Qt5.15.2 which triggers this issue, so we would need to manually build for RC and Release versions.

**Comment by liversedge** [comment] 2022-06-11 11:12
I think the simplest fix for this is to delay the metric refresh until the GUI has loaded at which point the qgraphicsscenes should have been created and allocated a worker thread.

**Comment by liversedge** [comment] 2022-06-12 08:27
Delaying the update to post GUI load doesn't work either. The GUI threads are allocated when needed, so we get a deadlock as soon as QtConcurrent::map runs i.e. as soon as the metric update is running the whole GUI will become unresponsive.

Will look at replacing the use of QtConcurrent for now.

**Closed** 2022-06-12 16:09 UTC
Labels: P1, performance
