### ISSUE TITLE
Activity list row height is not updated when data changes

### ISSUE THREAD

**Issue by batsonjay** [GoldenCheetah/GoldenCheetah#3074] opened 2019-04-11 15:26 UTC
Present in 3.5DEV build 1903, MacOS (though the regression appeared in 1901).

The following is a regression. I can reproduce this reliably:
1) Import a new activity from file (in this case, Zwift data)
2) Select Activities -> Details -> Workout; enter Sport
3) Select Activities -> Details -> Notes; enter Note
4) Select Activities -> Summary

The newly-entered event details _do not_ immediately appear under the event in the Activities pane (Upper-left corner). This is a regression; previously a mere pane switch (to anything) updated the display. (In fact, it previously updated the event with the Workout info when you switched from the Workout to Notes tab.)

The newly entered details DO appear after exit & restart of application.  They also DO appear in other places where "Calendar Text" is used.

See this screencast to see this behavior: https://screencast-o-matic.com/watch/cqfXIhZDeF

If multiple rides are imported from file simultaneously, this problem only appears in the FIRST file to be imported (which tends to be the oldest).  Details entered in the 2nd, 3rd, ... imported files appear as expected.

**Comment by amtriathlon** [comment] 2019-04-11 23:36
The only scenario when I can reproduce this is: activity is the first in Activities list AND calendar text is empty so the additional line is not present and it is not created when calendar text becomes non-empty.
In my typical setup this didn't happened since I have other fields additional to Notes which are present at the time of activity creation, the second line is present and adding Notes behaves as expected.

**Comment by liversedge** [comment] 2019-04-13 08:09
Ah. So this is not a regression. Its about the height of the row not being recomputed when data changes. Will look at that.

**Comment by batsonjay** [comment] 2019-04-13 11:40
I just realized I mis-stated the behavior. When multiple rides are imported notes are not displayed only for the ride that is at the top of the list, which is the NEWEST ride, not the oldest (as I state in the initial bug report).

@Mark, this does indeed feel like a row height issue because of another behavior I have seen that I failed to put in the report. If the list is sorted inversely to what you see in that screencast (with recent events at the bottom), a newly added row at the bottom of the list is displayed just a little bit too low the scroll region in this pane, and I can only see the top few pixels of the characters in the row. Also, I cannot scroll down to see that item. Restarting GC makes that (new) bottom row visible.

So check that as well when you’re checking for row height at the top of the list.

**Comment by MeisterP** [comment] 2019-04-30 06:06
> The newly entered details DO appear after exit & restart of application.

For me, just changing the sort order of the columns makes the text appear.

**Comment by sanfordhk** [comment] 2019-10-21 07:52
Thanks @amtriathlon for pointing me to this issue... 
I am able to reproduce this on Windows 10 as well as on a Mac.
![ridenavi](https://user-images.githubusercontent.com/8951463/67185905-76713080-f419-11e9-805e-1a12e1b44c99.PNG)
on 2.4 release the ride navigator row always has the correct height of 4 lines when adding a fit file. On Windows this seems to be correct if the new ride is sorted at the top or in the middle of the ride navigator but there is the display bug shown if the new ride goes to the bottom that gets fixed only on a column resort.
On Mac my new ride that goes to the top or bottom is always 1 line tall. Again this is fixed only on column resort.

**Comment by sanfordhk** [comment] 2019-10-22 02:29
On a Mac with the RideNavigator sorted by IsoPower, the newly added ride is not sorted correct, indicating incorrect timing of the RideNavigator refresh on adding of a new ride.
![Screen Shot 2019-10-22 at 9 52 43 AM](https://user-images.githubusercontent.com/8951463/67254898-137fa800-f4b2-11e9-9ac4-08e129b8d3a8.png)
Could this commit be related? https://github.com/GoldenCheetah/GoldenCheetah/commit/c6fe020aa0ce26a093e5bd964aa3d334eb35834d#diff-fc1f2a275163894093ab2b7fc098a72c
The redraw hack of sidebar in RideCacheModel was premature in case of a new RideFile?

**Comment by amtriathlon** [comment] 2021-01-28 00:33
As @liversedge commented before the problem is the row height not being recomputed when calendar text changes from empty to non-empty or vice versa, in the first case the additional lines are not displayed and in the second they are still displayed even when they are empty.

**Comment by paulj49457** [comment] 2021-02-07 23:05
I think this fixed by #3820

**Comment by paulj49457** [comment] 2021-05-03 13:07
Hopefully #3884 fixes the above  :)

**Closed** 2021-05-15 19:55 UTC
Labels: P3, UX
