### ISSUE TITLE
TCX Activity Export Incompatible With Garmin Connect

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2747] opened 2018-01-09 14:48 UTC
Exporting an activity as TCX and then trying to import into Garmin Connect fails. After some testing I have found that the GC export TCX looking like this:

```
<TrainingCenterDatabase>
   ...
            <Creator>
                <Name>The Sufferfest Training System</Name>
            </Creator>
   ...
</TrainingCenterDatabase>
```

Manually replacing the 'Creator' block with this as defined by schema fixes issue.

```
      <Creator xsi:type="Device_t">
        <Name>The Sufferfest Training System</Name>
        <UnitId>1</UnitId>
        <ProductID>1</ProductID>
        <Version>
          <VersionMajor>1</VersionMajor>
          <VersionMinor>0</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
        </Version>
      </Creator>
```

Strava and TrainingPeaks are resilient to this issue and import the file. Garmin Connect fails to import - presumably doing strict schema checking.

**Comment by amtriathlon** [comment] 2018-01-11 22:00
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2711

**Closed by amtriathlon** 2018-01-11 22:00 UTC
Labels: duplicate

**Comment by oberti** [comment] 2018-01-12 06:14
amtriathlon do you know the next relase date of GC ?
Thanks
