### ISSUE TITLE
Laps not showing correctly

### ISSUE THREAD

**Issue by avipilot** [GoldenCheetah/GoldenCheetah#3254] opened 2019-12-10 00:18 UTC
Lap1 overlaps Lap2, Lap3 etc... and their start locations are not at the same time. I created one for Lap 10 where I was interested in 1 minute power for the second time (which Interval finder got correctly).
Lap 3 should have been near the Peak 1 min power 1, and Lap 10 should have been near Peak 1 min power 2.  Something seems amiss with the location where Laps show up in the plot.

![image](https://user-images.githubusercontent.com/37384580/70484063-74356500-1a9f-11ea-9d6c-000d394ef24a.png)

![image](https://user-images.githubusercontent.com/37384580/70483997-3b958b80-1a9f-11ea-96f4-ace096c315ed.png)

Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right) and use the forums if you need help.

**Comment by amtriathlon** [comment] 2019-12-10 00:55
I don't understand what the problem is from your description, can you attach the activity file to try to recreate the issue?
If you export in GoldenCheetah Json all intervals will be included, you may need to zip the file to be able to attach it to this issue.

**Comment by avipilot** [comment] 2019-12-10 04:43
In the first picture I have selected the Lap1 (highlighted in blue). Notice how Lap2 and Lap3 are already inside Lap 1. Lap3 starting location should have been at the same starting point as Peak Power 1 min #1, just outside the blue selected range..... similarly, lap 10 is selected in the second picture, it should have been at the same location as Peak Power 1 min #2 location but it showed up earlier in this graph. I will be able to send the JSON files tomorrow to share this findings.

**Comment by amtriathlon** [comment] 2019-12-10 13:07
The problem is not "Laps not showing correctly" but the device laps are incorrect in the JSON file, you can check by yourself looking at interval properties on the sidebar.
The laps in the FIT file are Ok and I cannot reproduce the problem uploading that file to Strava and downloading the activity via Strava Sync with GC v3.5 RC2X.
Which GC version are you using?

**Comment by avipilot** [comment] 2019-12-10 19:17
To Recreate this issue, do the following.
1. Open the TCX file by itself. This shows everything correctly.
2. For the next step, you have to do the following.
2.1) Upload the TCX to STRAVA.
2.2) When GC downloads the file, it somehow will become corrupt as shown in the attachment.

My guess is that this happens because of some importing issues between GC and STRAVA. I don't know who maybe at fault here. But I am posting this on GC because that is where I see it messing up. On STRAVA, all the laps still show in the right location.

Right now it is creating more confusion with automatic import from STRAVA with laps.

**Closed** 2019-12-10 19:30 UTC
Labels: cannot recreate

**Comment by avipilot** [comment] 2019-12-10 20:38
Issue still exists in GC v3.5 RC2X when importing from STRAVA.
