### ISSUE TITLE
Allow FIT files to be used for workouts

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3376] opened 2020-03-20 21:25 UTC
Small code change will allow fit files to be loaded as ergfile. Recent case on user group someone had a fit file with no lat/lon data. They can't export as gpx because gpx has no distance, relies on gps data to derive distance. By allowing fit file to be used as ride file we can support ride of any slope/altitude based workout. More flexibile than gpx.

**Comment by liversedge** [comment] 2020-03-21 07:57
this can be done via the create workout wizard, it will use the currently selected activity.

**Comment by ericchristoffersen** [comment] 2020-04-16 16:03
WRT workout wizard, issue is not what workout wizard can import from, but what workout wizard can export to. Its little tiny brain only thinks in terms of crs. I only saw it being able to export a crs which is a very limited slope only file. What we want to be able to do is load from anything reasonable into the in-memory ErgFile format. I'd rather keep my workouts as a single file type. Today I prefer tts when possible, then gpx, then crs. We can't generate tts, we can emit gpx. Even better we can emit tcx which holds all kinds of fields and is viewable and editable with a text editor.

I dont understand why we want to tell anyone what is the workout interchange format that they should be using. Its all data stored in different standard conventions, let the user pick what they want for their own reasons. If we force them to go through the workout wizard we'll have exactly the same problem having to second guess what they consider to be the orthodox file type.

**Comment by liversedge** [comment] 2020-04-16 16:12
My apologies, I didn't realise the workout wizard was so useless!
It needs a brain transplant...

**Comment by liversedge** [comment] 2020-04-16 16:13
There *is* a fit file protocol specifically for workouts (not recorded activities).

**Comment by ericchristoffersen** [comment] 2020-04-16 16:37
What we're trying to do here is use a sharable open format that can hold the data needed for a virtual ride. Sort of like tacx' tts but open and easily generated. I don't think its our business to dictate the file interchange format. TCX for example is also really nice to use. RLV really sucks because it stores distance as a set of rates. Gpx sucks because it has no explicit distance, distance is derived by the reader.

The benefit of a generic file like fit and tcx is that they can hold all the data needed for a virtual ride. The same file can be used for both ergfile and for video sync. Is lovely that there is no longer any possibility of asynchrony. Also makes file management much easier. I am now able to have a single file in each of my 'rlv' ride directories. For my tacx rides I still use the tts because they work well. They have the same concept of a single file that acts as ride and video sync.

Things we want:
- a clear unambiguous distance (unlike gpx where distance is derived.)
- gps location (or just altitude if thats all there is, (or no location if there isn't any.))
- time so it can be used for video sync
- text editable
- gc read/writable (so we can start with existing workouts, filter and edit and smooth, then save and ride.)

I've been working with Peter Kanatselis to help him make virtual rides. Turns out the fit and tcx work perfectly and are simply awsome from a creation standpoint.

I'm really happy to no longer need to create rlv and or try to make correct tts.

**Comment by human705** [comment] 2020-06-07 23:52
I too like the idea of an open standard for a virtual ride/video sync file. I've been trying to figure out how to create an RLV file but i couldn't find anything helpful do i gave up. 

I've incorporated Eric's changes in my built and i must admit i was pleasantly surprised. I used a gpx file for the ride and my video started drifting almost immediately. Things got worse as time went on. It all changed when i was able to use the tcx file for vifdeosync. 

I haven't tried a fit file yet but it seems that it would be a great choice since it can be easily created from the Garmin site. Converting from gpx to tcx is a minor inconvenience. I'm working on a virtual rider feature that would allow the user to ride against an older ride. Allowing tcx and gpx would allow users to trade rides to compete virtually.

I hope this can be merged soon

Peter

**Comment by amtriathlon** [comment] 2020-06-15 22:52
Related to this, the EPM (Ergo Planet Movie) format looks interesting for this purpose: it contains video sync plus geolocation information in a clear and simple XML format so it is a good candidate to support in training mode with a nice library of free rides (http://wiki.ergoplanet.de/myor/roadmovie-galerie).

The problem is altitude, while contemplated in the format, is not included, a least in the examples I've seen, is always zero. I guess this is because it is redundant when you resort to the EPP (Ergo Planet Program) for slope data, but the EPP is a binary, and likely not published, format.

But if we adopt some variant of Eric's proposal, an alternative to be able to use those nice free synchronized videos would be to create an importer for EPM files to GC (this is easy https://github.com/amtriathlon/GoldenCheetah/commit/18358f3970fad7f80fcb397ea1523a67640a0beb) and then use standard GC tools to add the missing altitude data (Fix Elevation) and smooth slope (Fix GPS) to generate a file to be used in Train simulation mode.

**Comment by ericchristoffersen** [comment] 2020-06-16 00:32
Why do we care if people use any specific format in the privacy of their own pain cave? Does it hurt anyone if people want to use whatever random format? Is there a long term support consequence for gc that I'm not perceiving? Is peachy if we decide to support epp also, but thats orthagonal issue.

We're talking about how a few simple streams of data are packaged, what matters is that it does the job and how easy it is to operate upon.

Main thing I care about is being able to round trip my workouts through golden cheetah so I can edit them in the edit window and run the edit fixes against it, though even that doesn't matter once I'm done iterating.

**Comment by amtriathlon** [comment] 2020-06-16 22:58
Yes, I have concerns about usability (scan workouts will likely detect a ton of false positives if we add all formats we can import, and workout library management is not that flexible either) and support (in particular FIT file issues are a PITA to debug).

I introduced the EPM case because I think the use case to produce their own synchronized videos is and edge case without too much user demand, average users are more interested in to be able to use (ideally freely) ones and to increase the offering can be more attractive for them.

Since, in both cases, the input files need to be "massaged" using GC activity tools before to be used in Train, we don't need to (potentially) open a can of worms allowing all file formats, in my opinion we could agree on one flexible enough to enable these workflows.

**Comment by ericchristoffersen** [comment] 2020-06-17 00:21
The format thing is an edge case today because of barrier to entry. It is impossible to create rlv or tts (our only two supported videosync formats) without secret knowledge and a licensed v1 tacx software install. I wrote my own tool to produce an rlv and can vouch for how much that format suxx. Rlv definately arn't the right answer.

False positives. I agree it would be awful if someone were to accidentally hoover their entire activity directory as workouts. I definitely was not suggesting that someone should do that. I assumed that workouts are kept somewhere separate from everything else since the videos have such a significant file size that you can't not know where they live. It might be this accident could be avoided by refusing to scan the import directory, or a cancellable dialog that pops up with a list and warning before it is performed. But I also don't really think it is an issue since we allow gpx as workout today and haven't had complaints.

I don't see what allowing one format does for anyone, other than preventing people from using whatever random tool they want, but since gc can export to so many it is certainly a good enough practical solution to choose one so long as we pick a full-flavored format. I like tcx but am fine with anything that has the same explicit streams.

I'd be happy to write up instructions on how to manage workouts in gc. There are rules to follow if you don't want a big mess (naming, formats, etc). I personally find the scan really great but only because I carefully garden my workouts dir.

**Comment by amtriathlon** [comment] 2020-06-21 23:15
> I don't see what allowing one format does for anyone, other than preventing people from using whatever random tool they want, but since gc can export to so many it is certainly a good enough practical solution to choose one so long as we pick a full-flavored format. I like tcx but am fine with anything that has the same explicit streams.

Exporters are much less tested than importers and the data exported is generally a subset.
The one complete, and for which export followed by import gives the same result, is GoldenCheetah JSON. I vote to enable that one to be used directly as workout/videosync enabling these workflows.

**Comment by ericchristoffersen** [comment] 2020-06-22 02:00
Well that is why you make the big bucks Ale! Json sounds fine to me.

**Closed** 2020-06-22 17:47 UTC
Labels: P2, file format request, training view

**Comment by TWINGSISTER** [comment] 2021-04-05 14:12
I have some trouble in using EPM files (that has a nice online free library) on a 32 bit machine.  The 3.6 GC can import EPM but 
only 64 BIt GC is available, Yet I can process an EPM on a 64 bit machine and then save (what?) for later import on a 32 bit machine.
I can create and import workouts but I am stuck at video sync. Any help?

**Comment by amtriathlon** [comment] 2021-04-05 14:45
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
