### ISSUE TITLE
Weight units

### ISSUE THREAD

**Issue by timslau** [GoldenCheetah/GoldenCheetah#4013] opened 2021-08-18 15:49 UTC

**Comment by timslau** [comment] 2021-08-18 15:53
Hi

I have entered my weight in Athlete settings in Imperial units (162.5 lbs), but in most of the charts it records my weight as 162.5kg.
<img width="1429" alt="Screenshot 2021-08-18 at 16 52 13" src="https://user-images.githubusercontent.com/77543956/129930589-0fc62b4b-9e9f-4b63-98f0-1eec5ae81c9a.png">

**Comment by liversedge** [comment] 2021-08-18 16:38
I cannot reproduce this. Are you running v3.5 or later?

**Comment by timslau** [comment] 2021-08-19 09:20
Hi Mark

I am using the current build, 4007. I have been using GC since 2018.

I went into the options and my own athlete settings and converted them both to metric and it worked fine, showed weight correctly in the athlete weight chart, but when I converted it back to imperial, the table still had the weight title bar in kg, although the actual weights appeared as lbs. I have attached a screenshot.

I still prefer to measure my rides in miles (just a bit old school really).

I really appreciate the work done on GC. I am ageing cyclist but still like to measure and compare my efforts over the years.




Hope that this all makes sense.

Tim
Tim Slaughter
***@***.***

**Comment by amtriathlon** [comment] 2021-08-19 09:45
You can change the chart titles in chart config or use Reset layout and reset charts to default.
There was a bug fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/0dfa8f0e0082d05bb1ed5d7fca34dbb8e0bca2b9, but if you used the version with the bug weights need to be updated.

**Closed** 2021-08-20 13:56 UTC
Labels: Fixed already
