### ISSUE TITLE
Intervall view broken

### ISSUE THREAD

**Issue by weiznich** [GoldenCheetah/GoldenCheetah#3289] opened 2020-01-09 09:13 UTC
GoldenCheetah seems to be suddenly confused with my recorded intervals. It shows for all intervals the values from the "Entire Activity" interval (See the attached screenshot). Intervall times are recorded correctly if you click edit interval.

![Bug](https://user-images.githubusercontent.com/1674512/72053120-4faaf380-32be-11ea-9a75-79901eef64e2.png)

I'm quite sure that worked correctly in the past even on that version. It does not happen if you import a new activity, only if restart GoldenCheetah and look at existing activities. 
I'm not sure what other information are required to reproduce this, so just let me know if there is anything else you need.

Edit: Just tried to compare 2 such intervals, there the values are shown correctly.

**Version information**:
Build date: Dec 5 2019 20:34:28
Build id: 2981
Version: (developer build)
DB Schema: 152
Metrics: 364
OS: Linux
(Appimage from Github release of [release of version 3.5 RC2](https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC2))

**Comment by amtriathlon** [comment] 2020-01-09 11:06
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3244
Fixed in https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC2X

**Closed by amtriathlon** 2020-01-09 11:06 UTC
