### ISSUE TITLE
Exported TCX's rejected by Garmin Connect

### ISSUE THREAD

**Issue by thomasmoelhave** [GoldenCheetah/GoldenCheetah#2711] opened 2017-11-28 20:26 UTC
Following #2503 TCX files exported from Golden Cheetah are no longer accepted by Garmin Connect. If I manually go in and remove the 
```xml
           <Creator>
                <Name>GoldenCheetah</Name>
            </Creator>
```
entry the file imports cleanly. This behavior was also noticed by @amtriathlon on the commit itself (b2b3af4ce53e495591b) but I think it went unnoticed as the comment was made after the merge.
If you export a TCX file from Garmin Connect itself the following section is used:
```xml
      <Creator xsi:type="Device_t">
        <Name>fenix 3</Name>
        <UnitId>3910591682</UnitId>
        <ProductID>2050</ProductID>
        <Version>
          <VersionMajor>8</VersionMajor>
          <VersionMinor>8</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
        </Version>
      </Creator>
```
I tried simply adding the `xsi:type` and `<Version>` to the file exported by Golden Cheetah but that did not help either. Right now the only solution I know of is to go in and delete the full `<Creator>` entry manually, which is a shame.

BTW .FIT files don't import into Garmin Connect either (I don't know why) so doing a TCX export and removing `<Creator>` is the only way to go from Golden Cheetah to Garmin Connect that I know of.

Does anyone have any insight into what Golden Cheetah could put in `<Creator>` to satisfy Garmin?

**Comment by stschake** [comment] 2017-11-29 13:37
IIRC I added the <Creator> tag because Strava reads that to determine if altitude data came from a device with barometer and treats it differently.

Can you test if replacing the GoldenCheetah with a real device (i.e. "fenix 3") makes a difference? Otherwise I'd suggest making the creator field optional and only enabling it for Strava upload.

**Comment by thomasmoelhave** [comment] 2017-11-29 19:57
Yes, I wanted to reference #2535 as well but forgot, sorry.
The following creator section works for me:
```xml
      <Creator xsi:type="Device_t">
        <Name>Golden Cheetah</Name>
        <Version>
          <VersionMajor>15</VersionMajor>
          <VersionMinor>8</VersionMinor>
          <BuildMajor>0</BuildMajor>
          <BuildMinor>0</BuildMinor>
        </Version>
      </Creator>
```
Thus, it appears to be ok to write Golden Cheetah. I tried to simplify the above, but it's not ok to remove any of the version or build information and it is alsonot ok to remove the `xsi:type`.

**Comment by stschake** [comment] 2017-11-29 20:19
Well technically it shouldn't accept that either since it has no UnitId or ProductID that the schema says are required :)

Should we just fake out the version information?

**Comment by Joern-R** [comment] 2017-12-20 16:52
@thomasmoelhave @stschake 

I had a look as well / also tried to figure out how "others" create the TCX.

```
            <Creator xsi:type="Device_t">
                <Name>Garmin TCX</Name>
			    <UnitId>0</UnitId>
				<ProductID>20119</ProductID>
				<Version>
					<VersionMajor>0</VersionMajor>
					<VersionMinor>0</VersionMinor>
					<BuildMajor>0</BuildMajor>
					<BuildMinor>0</BuildMinor>
				</Version>
            </Creator>
```

The UnitID seems not to be necessary - nevertheless for completeness of schema. The Product Id is the one from "Garmin Training Center" in  the FIT definition - which is what Garmin is the same id they use when exporting to TCX.

It works for me both to Garmin Connect and Strava - can you please test your cases as well. And let us know if all use cases are covered by such a structure. I would suggest not to "promote" GoldenCheetah as a source/version - since we never know against which master data the content is checked. (One of my test upload showed a "Garmin Vector 3" as data source :-). So we should leave every unknown data "initial/0" as long as the upload works.

Thanks.
Joern

**Comment by thomasmoelhave** [comment] 2017-12-21 11:25
@Joern-R  that snippet works for my test file.
It's a shame that the "Creator" field cannot be used to give GoldenCheetah "credit" for making the file, ah well.

**Comment by Joern-R** [comment] 2018-03-11 10:54
Added a PR https://github.com/GoldenCheetah/GoldenCheetah/issues/2711 with the format change above (with one enhancement - which is special treatment for Zwift (which required to be correctly identified as virtual ride in Strava). Any objections/enhancements, please let me know.

**Comment by thomasmoelhave** [comment] 2018-03-12 11:25
This is great, I will test this out in the next development build.

In terms of possible enhancement. Is there a way to communicate to Garmin Connect that rides produced through Golden Cheetahs  trainer mode are "Indoor Rides"? I can't find that the TCX schema has native support for this. It's probably outside the scope of this issue anyway.

**Comment by liversedge** [comment] 2018-03-12 16:04
Fixed by #2815

**Comment by Joern-R** [comment] 2018-03-12 16:04
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/commit/95ce30a9a5fb1985ae54fb75ae688f032ab86561  (hopefully not creating regressions on other platforms)

@thomasmoelhave - I also had a look how to let Garmin know about indoor rides, but could not find something. If you, or anyone else reading this finds a proper solution, let me know - changing to logic how to fill the XML is a quick fix.

**Closed by liversedge** 2018-03-12 16:04 UTC
Labels: file format error

**Comment by flocsy** [comment] 2024-08-02 08:31
> @thomasmoelhave @stschake
> The UnitID seems not to be necessary - nevertheless for completeness of schema. The Product Id is the one from "Garmin Training Center" in the FIT definition - which is what Garmin is the same id they use when exporting to TCX.

Any chance you know where can I find the list of the ProductIds?
