### ISSUE TITLE
3970 appears to import Strava even when account removed

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#3088] opened 2019-04-25 09:01 UTC
Added Strava to permit auto import via Preferences > Athlete > Account, and disabled file import from Preferences > Athlete > Auto Import.

However, soon found this to not be usable as Strava exports gpx so much data (e.g. L/R balance) is lost.

Deleted Account and reverted to file import but GC 3970 still imports from Strava when opened, resulting in duplicate activities.

**Comment by amtriathlon** [comment] 2019-04-25 14:32
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2936

**Closed by amtriathlon** 2019-04-25 14:32 UTC
Labels: duplicate
