### ISSUE TITLE
Bookmarking audio and subtitles

### ISSUE THREAD

**Issue by TWINGSISTER** [GoldenCheetah/GoldenCheetah#3822] opened 2021-02-12 18:13 UTC
When I want to play a RLV I have to select RLV PGMF and AVI from a crowded tiny left panel. That's painful. It would be nice to have a bookmarking facility remembering this choice  and, possibly, a different starting point for my course and/or other conditions I modified once. I guess wouldn't be difficult to program VLC to add sound and subtitles e.g. "on the left you can see  the village of ..." or whatever. Commercial RLV vendors can have a great time in providing additional  content. 
For instance historical remarks about past races.  Cheers.

BTW, no 3.6 preview for 32bit.  Often people use outdated laptop in the training area in the basement. Not a good idea to drop 32 bit support  at least in the final release.

**Comment by amtriathlon** [comment] 2021-02-12 22:15
> When I want to play a RLV I have to select RLV PGMF and AVI from a crowded tiny left panel. That's painful. It would be nice to have a bookmarking facility remembering this choice and, possibly, a different starting point for my course and/or other conditions I modified once.

This is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/411

> I guess wouldn't be difficult to program VLC to add sound and subtitles e.g. "on the left you can see the village of ..." or whatever. Commercial RLV vendors can have a great time in providing additional content.
> For instance historical remarks about past races. Cheers.

Audio and subtitles can be embedded in the video, you could add yourself if you like to using standard programs.
OTOH, v3.6 supports text cues from most of the workout formats (ERG/MRC/CRS/ZWO/JSON).
 
> BTW, no 3.6 preview for 32bit. Often people use outdated laptop in the training area in the basement. Not a good idea to drop 32 bit support at least in the final release.

We don't plan to generate binaries for outdated hardware and operating systems, but interested developers or users can build by  themselves on that of other platforms, see for example: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Building-Golden-Cheetah-on-a-Raspberry-Pi-4-on-a-fresh-Raspbian-Buster-install

**Closed by amtriathlon** 2021-02-12 22:15 UTC
