### ISSUE TITLE
FR - Prevent OS from darkening screen or putting the computer into sleep

### ISSUE THREAD

**Issue by mk4th** [GoldenCheetah/GoldenCheetah#3828] opened 2021-02-23 18:32 UTC
Prevent OS from darkening screen or putting the computer into sleep, while training windows is open/active.
Especially when working with laptops that are not connected to power source, I find this one as important. When such thing happen, the communication with the ANT+ is gone and the training progress stops and cannot be resumed.

**Comment by amtriathlon** [comment] 2021-02-23 19:15
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2324

**Closed by amtriathlon** 2021-02-23 19:15 UTC
Labels: duplicate
