### ISSUE TITLE
Peak power curves in Metric Charts - limit number of data dots

### ISSUE THREAD

**Issue by Cander1336** [GoldenCheetah/GoldenCheetah#1296] opened 2015-01-31 01:51 UTC
In the deafult "PMC" tab using the Coggan Stress chart, I was trying to add 20 min Peak Power (among other durations) as a line curve, as it's very relevant and nice to have in a performance manager chart to see traning results. 

A common traning behavior that I do is regularly do specific 20min (etc) peak power intervals to track development. The problem when ploting these peak power curves is that you get a alot of data points (1 for each traning session, if the session was long enough naturally?), most of them being unrelevant and disturbring low results because you didn't try to peak in most of the sessions.

Is there some way to limit the number of data points that appear, preferbly setting up somehow that the only dots that apear is from these specific peak power sessions?

**Comment by liversedge** [comment] 2015-01-31 08:20
This is a duplicate of #1115 so closing.

**Closed** 2015-01-31 08:20 UTC
Labels: duplicate
