### ISSUE TITLE
Re-installed 3.5 RC1 - cannot sync with Strava past old date

### ISSUE THREAD

**Issue by jones-inc** [GoldenCheetah/GoldenCheetah#3237] opened 2019-12-04 16:55 UTC
Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right) and use the forums if you need help.
Hello. 
Uninstalled GC Dev version 3.5 back in February. Just re-installed last night, Set up authorization with Strava and attempted to Sync but it will not retrieve files newer than February 10, 2019. I can import manually any new file but sync will not find any files after said date.

My old Athlete profile still existed so I have created a new profile with the same results. 

Windows 10 64-bit version. Please let me know if you need any further information. thanks

**Comment by amtriathlon** [comment] 2019-12-04 17:27
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3216

**Closed by amtriathlon** 2019-12-04 17:27 UTC
Labels: duplicate

**Comment by jones-inc** [comment] 2019-12-04 17:30
Hello. I did try re-authorization 3 times last night with no success. I will try again tonight.

**Comment by amtriathlon** [comment] 2019-12-04 17:37
That will not solve this problem, wait for v3.5 RC2.

**Comment by jones-inc** [comment] 2019-12-04 17:43
ah. cool. thanks
