### ISSUE TITLE
Reconnect to last bluetooth device when bluetooth connection is dropped in middle of activity

### ISSUE THREAD

**Issue by navyjosh** [GoldenCheetah/GoldenCheetah#4039] opened 2021-09-11 21:29 UTC
My Kickr has issues when using ant+ so I use bluetooth.  In the middle of my workout, bluetooth connection dropped.  I could not get GC to reconnect to the kickr mid-workout so I had to stop the workout early.

It would be nice if the training device connection could be established mid-workout for situations where the connection drops.

Attached is log during the dropped connection.

```
[17:16:50.453] debug: BTLE write load command  "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}"   "42:d5:00" (Train/BT40Device.cpp:1049)
[17:16:50.681] debug: BTLE wrote to  "Wahoo KICKR 0E24"   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:d5:00" (Train/BT40Device.cpp:685)
[17:16:51.453] debug: BTLE SetLoadErg  213   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:d5:00" (Train/BT40Device.cpp:953)
[17:16:51.453] debug: BTLE write load command  "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}"   "42:d5:00" (Train/BT40Device.cpp:1049)
[17:16:52.454] debug: BTLE SetLoadErg  213   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:d5:00" (Train/BT40Device.cpp:953)
[17:16:53.453] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:54.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:55.453] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:56.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:57.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:58.453] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:16:59.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:17:00.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:17:01.453] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:17:02.454] debug: BTLE SetLoadErg  71   "{a026e005-0a7d-4ab3-97fa-f1500f9feb8b}" "42:47:00" (Train/BT40Device.cpp:953)
[17:17:02.873] debug: service state changed  QLowEnergyService::InvalidService for device "Wahoo KICKR 0E24"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:230)
[17:17:02.875] warning: Aborting onCharWriteFinished due to disconnect (unknown:0)
[17:17:02.875] debug: Lost connection to "58-14-88-DA-A2-67"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:125)
[17:17:02.875] debug: Connecting to device "58-14-88-DA-A2-67"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:95)
[17:17:02.884] warning: Error: Local adapter is powered off (unknown:0)
[17:17:02.884] warning: Controller Error: QLowEnergyController::ConnectionError for device "58-14-88-DA-A2-67"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:119)
[17:17:02.884] debug: Lost connection to "Wahoo KICKR 0E24"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:125)
[17:17:02.884] debug: Connecting to device "Wahoo KICKR 0E24"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:95)
[17:17:02.892] warning: Error: Local adapter is powered off (unknown:0)
[17:17:02.892] warning: Controller Error: QLowEnergyController::ConnectionError for device "Wahoo KICKR 0E24"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:119)
[17:17:02.892] debug: Lost connection to "USB ANT STICK"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:125)
[17:17:02.892] debug: Connecting to device "USB ANT STICK"   "{00000000-0000-0000-0000-000000000000}" (Train/BT40Device.cpp:95)
[17:17:02.901] warning: Error: Local adapter is powered off (unknown:0)

```

**Comment by amtriathlon** [comment] 2021-09-11 21:38
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2246

**Closed by amtriathlon** 2021-09-11 21:38 UTC
Labels: duplicate
