### ISSUE TITLE
Discrepanies in .fit data and .tcx/xlsx data (imported from Movescount - PT G3 via Ambit2S), GC 3.2.0

### ISSUE THREAD

**Issue by M135437** [GoldenCheetah/GoldenCheetah#1926] opened 2016-04-12 21:34 UTC
Hello,

I noticed approx 7% difference in Power, Speed and Cadence values in Golden Cheetah compared to Movescount and Strava for the same efforts, whereas the usual explanation of GC computing pauses did not clarify - the same appeared in workouts where the clock was never stopped.

A quick look at the Ride graphs probably indicated what the issues is about - GC gets zero values from somewhere for Power, Speed, Cadence and Heartrate- as seen in the attached screenshot:
![2016-04-13 00_30_43-guineapig](https://cloud.githubusercontent.com/assets/18428402/14476211/160e4224-010f-11e6-8680-e77684014f98.png)

I'll be sending the files via mail.

Please kindly check if this is a known error or a new bug and let me know

Regards,
Mikk

**Comment by M135437** [comment] 2016-04-12 21:40
Sent the files via mail now.

Forgot to add - when importing the same ride from a .tcx, GC seems to get it "right" (values have an acceptable/almost exact match with the Strava and Movescount equivalents):
![2016-04-13 00_38_56-guineapig](https://cloud.githubusercontent.com/assets/18428402/14476419/56bbcfb6-0110-11e6-9ad4-9f3516f71ea8.png)

**Comment by henolo** [comment] 2016-04-30 10:55
I have observed the same behavior, but with even more "noise" - screen dump enclosed.
Ambit3V to movescount then FIT export into GC. (movescount TCX export looks ok)
Importing this fit-file into firstbeat Athlete looks ok.
![fit noise](https://cloud.githubusercontent.com/assets/15927134/14935466/b44174e0-0ed2-11e6-9d34-ed6020fbd526.png)
rgs
Henrik

**Comment by amtriathlon** [comment] 2016-04-30 13:39
Have you tried to import the original SML file?

El sábado, 30 de abril de 2016, henolo <notifications@github.com> escribió:

> I have observed the same behavior, but with even more "noise" - screen
> dump enclosed.
> Ambit3V to movescount then FIT export into GC. (movescount TCX export
> looks ok)
> Importing this fit-file into firstbeat Athlete looks ok.
> [image: fit noise]
> <https://cloud.githubusercontent.com/assets/15927134/14935466/b44174e0-0ed2-11e6-9d34-ed6020fbd526.png>
> rgs
> Henrik
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1926#issuecomment-215954873>
>


-- 
Alejandro.

**Comment by henolo** [comment] 2016-05-01 19:48
When importing the original SML for this training activity I get smoother data - BUT HR disappears completely !! Have not tried this before so don't know if it is just this training or all. But for this training I tried it several times and no HR data for all tries. 
So for now the best workaround is to do GC-import of the TCX export from movescount.
Apparently there is something weird going on in the FIT import (since I can import data into Athlete without any randomness).
/Henrik

**Comment by M135437** [comment] 2016-05-02 06:24
According to Strava (the issue appears on the Speed value there, but not on other values - so I reported a case there as well), the zeros are "display[ed] this way [due to] how the GPS track points are recorded with [the] device. It records in these short burst intervals (see attached picture) [we] tried to change on [our] end to smoothen out the graph for you for the example activity, but unfortunately there isn't anything we can do on our end."
<img width="626" alt="screenshot 4-16-16 12-24 pm" src="https://cloud.githubusercontent.com/assets/18428402/14944511/ff351ade-0ffd-11e6-8a16-bc1049f1b34e.png">

Not sure if they got to the root of the issue or did any actualy debugging of the .fit.

I've been unable to debug any of the .fit and .sml contents myself and am making a guess here, but it seems either a Suunto .fit export issue or uncontrolled change of the .fit API from their side. Created [TT554527] at Suunto ~20 days ago for this, but haven't received any response yet despite the 72-hour SLA.

**Comment by henolo** [comment] 2016-05-02 09:06
There is a surprisingly high flow of FIT SDK updates on the thisisant.com (16.74 is currently the latest for FITSDK 1X). I was unfortunately not able to interpret the release notes to understand if it might have something to do with this or not. If I find some time I will try to run the FitCSVtool to see if it might show something interesting.
/Henrik

**Comment by henolo** [comment] 2016-05-27 13:09
The FIT SDK might be more stable now:

--- from thisisant.com ---
May 02, 2016
FITSDK 20.00.00 Update

Version 20.00.00 of the FIT SDK is now available on the downloads page. Includes new FIT 2.0 features, iOS Universal Library, and performance improvements in the C++ SDK.

--- end ---

rgs
Henrik

**Comment by amtriathlon** [comment] 2016-05-27 13:38
> When importing the original SML for this training activity I get smoother data - BUT HR disappears completely !! Have not tried this before so don't know if it is just this training or all. But for this training I tried it several times and no HR data for all tries. 

This was due to HR not present in periodic samples but only as R-R data in some SML files, in the last published development build there is a patch to convert R-R data to sample level HR at import, time.

**Comment by liversedge** [comment] 2016-05-27 13:53
can this be closed?

also, for info we don't use the FIT SDK as its closed source and not available on Linux.

**Comment by henolo** [comment] 2016-05-27 16:49
Not sure.

As far as I understand it, it is the usage of several data records for one timestamp in FIT files from suunto. And only the last data record makes it into GC, the data in others becomes "0", so this shouldn't be too hard to correct (I hope). 

As workarounds one currently can

0) import TCX, but then all data when not moving is zeroed (this doesn't work with my MTB group rides).

1) import the SML (thanks to the r-r translation!!) 
But this only works IF you synced with movescount via a Computer.
If the watch sync'ed via the smartphone app there is no SML file and the smartphone app background service just grabs the training files when it finds the watch! Big Surprise!
Unfortuantely suunto have no dedicated setting to disable this app-sync so other more useful features are turned off as well if you want to disable it. So one need to turn this on and off and will forget it now and then and the there is not SML...

2) one can use the GC error cleaning tool and use merge files and well it all takes a while until you get "most of the" data into GC.

So IMHO it would make things much easier if the GC FIT import just worked with suunto generated files. And this will for sure work better for non-techies.  

Regarding FIT SDK, had not read that one is not allowed to pass this SDK on to others.

**Comment by amtriathlon** [comment] 2016-05-27 21:23
I is weird Movescount doesn't let you export their native file format...

Anyway, the problem seems to be related to the way the SML file is translated to FIT: in SML they have 2 kinds of sample records: GPS for coordinates and Periodic for the rest of the data, Movescount probably is generating one FIT record for each of them so, when a GPS sample appears it has all other data as zeros and GC adds it instead to use it to update GPS coordinates without to generate a new (periodic) record as it is done while processing SML files.
If you post a sample file (both SML and FIT for the same activity) this theory could be tested and the complexity of the change evaluated.

**Comment by henolo** [comment] 2016-05-28 13:09
AM, Have you looked at excel file that I already uploaded (on may 2)  that shows the contents of the FIT file in "plain view"? [Hope you have dual screens since it is a lot of columns]
For a single timestamp value there is either one or two data records. 
When there is two one of them, one is "normal training data" the other is coordinates [so this matches your SML theory].
Suunto use the possibility to only provide data for some fields in the previous definition. So it is only the actually provided fields in the very last data record for a given timestamp that ends up with useful data in GC. (typically the coordinates).

Uploaded "all" the files for this training:
[April2016_30_09_43_53.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/287713/April2016_30_09_43_53.zip)

/Henrik

**Comment by amtriathlon** [comment] 2016-05-30 14:04
Yes the problem is gps coordinates come on separate record from the rest of the data with the same timestamp, currently GC discards the second record assuming it is a duplicate, so the behavior depends on the order, which is no always the same:
-when "gps" record comes first the rest of data is lost and only gps coordinates are recorded
-when "data" record comes first gps coordinates are lost and the rest of data is recorded
The zeros you see in edit corresponds to the lost data.

**Comment by henolo** [comment] 2016-05-30 16:54
Ok, then my assumption that it was the last one that was kept was premature and wrong - indeed.

There are real data record duplicates occasionally also, E.g. two times just in the beginning of my upploaded file(s) and not even with the same data for a given property (in this case altitude). 
So some kind of roboust data record aggregation/merge approach is needed. Maybe one can just overwrite (potentially) earlier data until there are no more data records for a given timestamp (or something like that) then the last given numbers will be used in GC?

**Comment by amtriathlon** [comment] 2016-05-30 17:41
A simple and robust, albeit tedious to implement, solution could be to update each field not present in the stored sample and present in the new record when a duplicate timestamp happens

**Comment by M135437** [comment] 2016-05-31 08:17
I've updated Suunto in their support reference #TT554527 regarding the discussion here. Unless anyone minds, I would propose to keep this issue open at least until their response is received (taken into consideration that since they are providing End User support, a response to the generic issue/3rdParty implications of their export files may not be given at all, but I'm optimistic until now).

**Comment by amtriathlon** [comment] 2019-04-17 12:13
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/55ec3973c3392ac664b173612b4eebcbe61f1f9d, Bryton files also have repeated timestamps.

**Closed by amtriathlon** 2019-04-17 12:13 UTC
Labels: file format error
