### ISSUE TITLE
KPI Tracker trend

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3574] opened 2020-08-17 08:51 UTC
In the KPI tracker chart i think thet the 60 min peak power shows bad data, an example:

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90376961-93958080-e077-11ea-8107-8f3ca3d54f05.png)

**Comment by amtriathlon** [comment] 2020-08-17 12:06
It looks like a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3566
Which GC version are you using?

**Comment by sabata4** [comment] 2020-08-17 14:09
this image is from the august 15 snapshot... i downloaded yesterday.

**Comment by amtriathlon** [comment] 2020-08-17 14:38
All these charts are instances of Metric Trends charts, so you can check if the values in curve mode match those values, go to the individual activities in Activities view and check the values for the metric in question for the involved activities, etc.
I cannot reproduce this readily and just a screen capture is not helpful.

**Comment by sabata4** [comment] 2020-08-17 17:58
yes,... maybe it's not the best image to show that i suppose that it's an issue: 

I try to explain better:
![Screenshot_2](https://user-images.githubusercontent.com/41129474/90428141-d5e4af00-e0c3-11ea-90cc-0eea3aee2471.png)


My run's last 6 weeks power profile where you can see some 60 min peak

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90427922-843c2480-e0c3-11ea-84f8-4cd04ddcb9fa.png)
 
i hope that with this i could explain well.
and here the same run's with the KPI Tracker and where you can see the 60 min peak with differnet values:

**Comment by amtriathlon** [comment] 2020-08-17 18:16
May be that chart is corrupted, you can try remove and recreate or use reset layout/reset to default

**Comment by sabata4** [comment] 2020-08-17 18:56
I tried to reset to default and tried to change all the data ranges.... and the problem es exactly the same.... the peak in 5 minutes its around 200 and the 60 min peak it's arround 10.... in the table and the curve...

![Screenshot_3](https://user-images.githubusercontent.com/41129474/90433405-10eae080-e0cc-11ea-80da-62e78286a7a6.png)

**Comment by amtriathlon** [comment] 2020-08-17 20:02
You can check the chart options to see how that curve is configured.

**Comment by sabata4** [comment] 2020-08-17 20:24
you are roght!! the chart is configured with the speed! It's not an issue!

**Closed** 2020-08-17 20:44 UTC
Labels: cannot recreate

**Comment by sabata4** [comment] 2020-08-17 20:50
only one thing.... the chart is a preconfigured chart then maybe the label have to be corrected, no? then put speed and no watts.

**Comment by sabata4** [comment] 2020-08-26 21:48
Tested in the last snapshot (25/08)
