### ISSUE TITLE
Compare Pane to compare activity file of same activity between athletes

### ISSUE THREAD

**Issue by ninardos** [GoldenCheetah/GoldenCheetah#2665] opened 2017-10-23 06:32 UTC
When comparing activities for two or more athletes I am missing some features to enable better analyses for activities comparison.

a) shift one or more activities by a certain amount of time to line up activities perfectly. This could be done manually or maybe supported by GC (similar as in "combine activities -> add new metrics), maybe based on GPS data, global time.... 
b) select / define intervals simultaneously when in compare mode and show interval key metrics (or differences) in interval window
c) In many cases a "delta" view would provide more insight.
d) maybe it would be even possible to automatically detect intervals where power data do seem to not match up, automatically or assisted. This would be helpful for race analyis.

Some explanations:

ad a) a first possibility that comes into mind is to cut an acitivty to a defined interval or by time, but somehow the existing "activity -> split assistant does not seem to be able to do simple cutting / exporting to a new activity of a certain time intervall from one activity". Maybe I am just missing something.
Currently even when I select "show by time of day", the activities are lined up by start time
![image](https://user-images.githubusercontent.com/28820522/31875047-a6f69ec4-b7cc-11e7-9d49-52eafada1d8f.png)

ad b) The current workaround for me is to define intervals separately for each athlete/activity, which involves calculating adjusted times and doing it multiple times (once per activity to compare). It would be far easier and in the end enable better analyses to do this on the fly, simultaneously and when in compare mode.
It also would be nice to show interval metrics / differences for current selection live, i. e. when defining the interval by mouse

ad c) For example the differences in power output might be significant (e. g. ~30-50 W) but the scale when just plotting each power in the same pane covers a huge range (typically from 0 to > 1000 W), so that the differences do not show visually. Even Smoothing at times reduces the problem, but still, e. g. with a 5 minute smooth, the whole power scale is around 0 to >400 W, where 30 W difference does not stick out as much as it would.

ps: if this is the wrong place for this type of request / questions, please indicate where it should go

**Comment by amtriathlon** [comment] 2020-11-23 23:26
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2665

**Closed by amtriathlon** 2020-11-23 23:26 UTC

**Comment by julian-klode** [comment] 2021-09-06 16:11
Hey, @amtriathlon, you marked this issue as a duplicate of itself. What's the real one?

**Comment by amtriathlon** [comment] 2021-09-06 16:33
https://github.com/GoldenCheetah/GoldenCheetah/issues/1178 is the compare mode wish list.
