### ISSUE TITLE
Suggestion: with multiple intervals are selected, make Delete Interval erase all of them

### ISSUE THREAD

**Issue by Mrnofish** [GoldenCheetah/GoldenCheetah#2489] opened 2017-04-27 22:15 UTC
When multiple intervals are selected, Delete Interval only erases one interval, the one whose chained menu was opened, instead of the entire selection.

It is thus necessary to delete them manually, one at a time, which is inconvenient and time-consuming, and also inconsistent with UI conventions.

**Comment by amtriathlon** [comment] 2017-04-27 22:30
This is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2233, which is already solved for v3.5, you can test it on current development build.

**Closed by amtriathlon** 2017-04-27 22:30 UTC
Labels: duplicate
