### ISSUE TITLE
Train View - "RouteDistance" data series resolution

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#3589] opened 2020-09-07 05:38 UTC
In Train view, the current resolution in distance telemetry (data series = Routedistance) is 1km. 

When training (or doing trials), this is far too big to assess changes in the file at specific points because pushing rewind or fast forward pushes the workout by 1km. 

The user could have an option to change this from 1km to 0.1, 0.25, 0.5, 0.75 kms etc for finer resolution.

**Comment by ericchristoffersen** [comment] 2020-09-14 18:37
I am not seeing this behavior. I also use a routedistance tile and it shows routedistance displayed to 3 digits, so gives meter resolution.

![routedistance](https://user-images.githubusercontent.com/46055145/93123609-43f9a300-f67d-11ea-9660-02e60743430a.JPG)

I'll need more to reproduce the issue. Could you share the train file you are using?

**Comment by rgeorge1985** [comment] 2020-09-14 19:53
> I am not seeing this behavior. I also use a routedistance tile and it shows routedistance displayed to 3 digits, so gives meter resolution.
> 
> ![routedistance](https://user-images.githubusercontent.com/46055145/93123609-43f9a300-f67d-11ea-9660-02e60743430a.JPG)
> 
> I'll need more to reproduce the issue. Could you share the train file you are using?

Hi Eric,

Perhaps there's a setting somewhere to set the resolution? I'm seeing integers for this metric.

**Comment by ericchristoffersen** [comment] 2020-09-15 20:26
I remember fixing this a long time ago so I dug in... well... the fix for this is in a pull request that is still pending. I am working off the branch with the fixes so didn't see it. Sorry!

Pull request is:

#3442

**Comment by amtriathlon** [comment] 2020-11-13 00:51
Duplicate of #3499

**Closed by amtriathlon** 2020-11-13 00:51 UTC
Labels: P3, gui / cosmetic error, training view
