### ISSUE TITLE
activity compare section not resizable

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3285] opened 2020-01-05 16:37 UTC
Hello,
the compare section in the activity area is no longer resizable.
Wehn I turn on the compare section it appears in the bottom area
But as soon as I try to change the height of the compare section by clicking on the title bar the whole sections disappears. When I stop clicking then only the title bar appears at the bottom of the main frame.

I'm using Build 3892

greeting 
  Marco

**Comment by amtriathlon** [comment] 2020-01-06 20:05
I can reproduce this on Windows and Linux v3.5RC2 builds, but I don't know what is producing this behavior, much less how to fix it.

**Comment by amtriathlon** [comment] 2020-01-08 12:36
Some additional testing (on Linux) shows it is a problem in (default) Tabbed view, switching to Tiled view solves the issue and, this is the weirdest part, compare pane remains resizeable after switching back to Tabbed view.

**Comment by liversedge** [comment] 2020-01-08 13:11
Ooh. It might be worth removing charts 1 by 1 to see if there is a specific chart that is the problem.
Also, opening each tab before trying to resize the compare pane to do an initial show ?

**Comment by amtriathlon** [comment] 2020-01-08 13:31
Opening each tab before to resize doesn't changes the behavior, but removing the Summary chart or changing the chart order so Summary is not the first tab, fixes the issue, even when Summary is selected at drag&drop time.

**Comment by amtriathlon** [comment] 2020-01-08 14:13
Interestingly this doesn't seems to happen with newly created athletes or after doing a reset layout in Analysis View.

**Comment by amtriathlon** [comment] 2020-01-08 14:40
Interestingly this doesn't seems to happen with newly created athletes or after doing a reset layout in Analysis View.

**Comment by amtriathlon** [comment] 2020-01-08 20:10
Summary:
- This issue doesn't happen with athletes created with v3.5 RC2X
- For existing athletes it can be solved using View > Reset Layout in Activities view, to preserve customized charts they can be exported to files before Reset Layout and imported afterwards.

@Genussradler can you confirm this behavior?

**Comment by Genussradler** [comment] 2020-01-09 16:53
> 
> 
> Some additional testing (on Linux) shows this is a problem in (default) Tabbed view, switching to Tiled view solves the issue and, this is the weirdest part, compare pane remains resizeable after switching back to Tabbed view.

**Comment by amtriathlon** [comment] 2020-01-10 19:13
I am closing this since it doesn't happen when newly created athletes and reset layout on activity view fixes it for existing users, which is a good idea anyway to have updated charts.

**Closed by amtriathlon** 2020-01-10 19:13 UTC
Labels: gui / cosmetic error
