### ISSUE TITLE
Properties of workout changes everytime I exit program

### ISSUE THREAD

**Issue by MichCro** [GoldenCheetah/GoldenCheetah#2726] opened 2017-12-14 11:37 UTC

**Comment by MichCro** [comment] 2017-12-14 11:41
Every time I make a workout and then save and exit the program to then start it up again the time and watt values in properties has changed. For example if I add in 10x40s@380r20@160 and then come back it'll change it to 10x39s@380.23r19@160. Please fix this issue
/Thanks in advance

**Comment by MichCro** [comment] 2017-12-14 11:48
I checked the saves for the workout and the problem is that for example 40s in the document is 0.67 minutes which rounds of every time the workout is opened again.

**Comment by Joern-R** [comment] 2017-12-20 15:50
Thanks for analysing. The root cause is that workouts created in GoldenCheetah are stored in the widely used/popular .ERG format - in which time is defined in fractions of minutes. I created such a workout in other tools like Today's Plan exported the Workout as .ERG and ended up with exactly the same situation. 

Only fix for this would be to use a different format for workouts created in GoldenCheetah - which would be a feature request - and I an not certain if/when someone will pick this up. To not loose the analysis I put it into the parking lot.

**Comment by amtriathlon** [comment] 2020-07-07 23:44
I am closing this since the time rounding is due to the use of erg file format and it can be avoided saving as zwo format.

**Closed by amtriathlon** 2020-07-07 23:44 UTC
Labels: training view
