### ISSUE TITLE
Crash: Train (Erg + Kickr)

### ISSUE THREAD

**Issue by bernmc** [GoldenCheetah/GoldenCheetah#1995] opened 2016-06-08 10:40 UTC
GoldenCheetah_V4.0_DEV1605_64bit (last month's release)

Crash while using GC and an ErgDB file to control the Wahoo Kickr (updated to latest firmware)

Crash occurred when I tried to adjust the Kickr using the up/down arrow on GC's train page - approx 15 min into the workout.

Unable to reopen GC with the same athlete until I'd opened with another and gone to the train page with that athlete.

[gccrash.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/304522/gccrash.txt)

**Comment by amtriathlon** [comment] 2019-05-02 00:00
I'm closing this since it refers to an old development version, please reopen if you can reproduce it with the last devlopment build.

**Closed by amtriathlon** 2019-05-02 00:00 UTC
Labels: cannot recreate, crash
