### ISSUE TITLE
Overview chart doesn't have a 'more' button; hence can't remove it.

### ISSUE THREAD

**Issue by armorrc** [GoldenCheetah/GoldenCheetah#3155] opened 2019-09-02 21:48 UTC
Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right) and use the forums if you need help.

**Comment by liversedge** [comment] 2019-09-03 04:24
duplicate of one raised by @armorrc and also #3093 and also comment added to #1305.

**Closed by liversedge** 2019-09-03 04:24 UTC
