### ISSUE TITLE
Dev 3.6 crashes after reading user data

### ISSUE THREAD

**Issue by vk7rb** [GoldenCheetah/GoldenCheetah#3429] opened 2020-05-03 03:13 UTC
Thought I would try the new Dev 3.6 release but it keeps crashing just after the indicator that comes up hits 100% and with the latest one using Qt, this crash is still occurring even after installing Qt onto the system.

Any advice would be much appreciated as to how to get it running without crashing.

[crash_1249_030520.log](https://github.com/GoldenCheetah/GoldenCheetah/files/4569563/crash_1249_030520.log)
[crash_1249_030520.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4569564/crash_1249_030520.zip)

**Comment by amtriathlon** [comment] 2020-05-03 13:11
Have you installed the optional VC++ redistributable in setup?

These builds are based on Visual Studio Community 2019 version 16.5.4, so to install the included VC++ redistributable may be necessary on your system.

**Comment by amtriathlon** [comment] 2020-05-03 13:35
Looking at the crash file I found it includes python36.dll, which indicates a previous version uploaded and taken down, the current one includes python37.dll, can you download and install again?

**Comment by liversedge** [comment] 2020-05-03 16:44
mick drake emailed me privately after installing the latest, crashes with:
Here is the crash log?
Unhandled exception 0xc0000005
RAX=d1c7c12600000002 RCX=23e2d357e58 RDX=23e2d357e50 RBX=d1c7c12600000002
RSP=ed1c0fc1b0 RBP=ed1c0fc400 RSI=1 RDI=23e2d357e58
R8=ed1c0fc1c0 R9=ed1c0fc1c0 R10=3 R11=246
R12=ed1c0fc2a0 R13=0 R14=0 R15=23e2e8bf490

Qt5Core.dll!QMutex::lock+0x26
Qt5Network.dll!QNetworkConfigurationManagerPrivate::configurationAdded+0xd3
Qt5Network.dll!QNetworkConfigurationManagerPrivate::qt_static_metacall+0xfd
Qt5Core.dll!QObject::event+0x183
Qt5Core.dll!QCoreApplication::notifyInternal2+0xa4
Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents+0x22b
Qt5Core.dll!QEventDispatcherWin32::processEvents+0x70
Qt5Core.dll!QEventLoop::exec+0x1eb
Qt5Core.dll!QThread::exec+0x89
Qt5Core.dll!QThread::start+0x36d
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21

Possibly ssl related?

(it also crashes for me on windows 10)

**Comment by amtriathlon** [comment] 2020-05-03 17:32
> Possibly ssl related?
> 
> (it also crashes for me on windows 10)

Can you try replacing libssl and libcrypto dlls with the ones included in Qt 5.14.2 by the Qt online installer: Qt\Tools\OpenSSL\Win_x64\bin ?

**Comment by amtriathlon** [comment] 2020-05-03 18:43
I could reproduce a crash at startup when the athlete has a Python chart, Python embedding is enabled, but config points to a non-compatible Python version, which may happen for users previously using Python36 since this version needs Python37.
In this case starting with --no-python avoids the crash, I am not sure this is the same reported here, but it may worth a try.

**Comment by liversedge** [comment] 2020-05-03 19:18
I tried launching with --no-python and it made no difference.
After downloading qt5.14.2 the only ssl/crypt libs I could find were in the qtcreator folder and 32 bit.

**Comment by liversedge** [comment] 2020-05-03 19:22
Also, view reset layout to get rid of anything python and disabling python altogether had no effect either.

**Comment by liversedge** [comment] 2020-05-03 19:34
It works for me now:
- I deleted the old Program Files/ GoldenCheetah folder. And downloaded and installed again.
- I installed the vc redist and chose to repair.
- I then shutdown (not restart).
- After booting the build works just fine.

Either; something was left behind in the install directory -or- vc repair did something.
I am pretty sure I rebooted after install the first time.

**Comment by liversedge** [comment] 2020-05-03 19:36
![version](https://user-images.githubusercontent.com/142876/80923805-b6787f00-8d7d-11ea-9205-879bc6c66015.PNG)

**Comment by liversedge** [comment] 2020-05-03 20:11
I think the recommendation here is to:
1. remove the old folder in program files -- delete it or rename it.
2. install the vc redist and then shutdown completely.
3. lets look at making the installer delete the folder contents before installing -or- insist on a new folder -or- warn it will be zapped ?

Closing the issue as we have a workaround / resolution that shows the build is fine.

**Closed by liversedge** 2020-05-03 20:11 UTC
Labels: cannot recreate

**Comment by amtriathlon** [comment] 2020-05-03 20:26
Yes, we should recommend to uninstall first the existing version if the idea is to use the same folder.

**Comment by liversedge** [comment] 2020-05-04 10:07
Confirmed in the mailing list by another user (Mick Drake):
On Monday, 4 May 2020 09:30:21 UTC+1, Mick Drake wrote:

    Thanks Mark, installing to a new folder sorted it
    Mick
