### ISSUE TITLE
Feature request: Accept R/L-balance with right-flag set to 0 again

### ISSUE THREAD

**Issue by grmpl** [GoldenCheetah/GoldenCheetah#4096] opened 2021-12-04 20:13 UTC
In Version 3.6 a value of 0 in the right-flag of the L/R-balance is not accepted anymore, as according to FIT-specification only a 1 in the right flag is allowed. But a flag which does not allow another value does not make sense. 
If logging with Assioma pedals and a Wahoo Bolt, the L/R-balance is recorded with flag set to 0 because it is recorded as a left-balance and not a right-balance. Since v3.6 therefore data is not imported anymore. 

Please revert the logic back to v3.5 where a value of '0' will be accpepted and just does not revert the balance values.

**Comment by amtriathlon** [comment] 2021-12-04 22:03
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/4067

**Closed by amtriathlon** 2021-12-04 22:03 UTC
Labels: duplicate
