### ISSUE TITLE
60 min Peak Power not correct in KPI Tracker (Library tab)

### ISSUE THREAD

**Issue by steeler-fanatic** [GoldenCheetah/GoldenCheetah#3821] opened 2021-02-12 17:11 UTC
On the Tracker page, my 60 minute power shows correctly as varying between 214 and 219 watts over the December - February time period.  On the Library tab in the KPI Tracker, the values range from 35 - 39 watts in both the table and graph views.  I'm am using a MacBook Pro (15-inch, 2017 version) tuning macOS Big Sur Version 11.2.1.  The GoldenCheetah build date is Nov 15 2020 20:12:01 Build id: 4002 Development build.

**Comment by amtriathlon** [comment] 2021-02-12 17:54
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3574

**Closed by amtriathlon** 2021-02-12 17:54 UTC
