### ISSUE TITLE
Response to desktop scaling in Windows

### ISSUE THREAD

**Issue by cleveruplink** [GoldenCheetah/GoldenCheetah#1656] opened 2015-11-12 16:08 UTC
For high resolution screens, it's pretty normal for Windows to scale up text, images and apps; especially in Windows 10.

Golden Cheetah doesn't appear to adopt these scaling settings and therefore on a high resolution laptop screen (>full HD) with scaling of greater than 100%, the menu text appears oversized, the menu icons appear too small and are in some cases cropped, and the text on summary data screens and graphs is tiny. I've attached a screenshot to show the overall effect.

Is it possible to inherit the scaling options from Windows rather than setting them at explicit values?

![golden cheetah scaling screen](https://cloud.githubusercontent.com/assets/15819584/11123420/7fe8c56e-8957-11e5-91fd-b09c1745ee9e.PNG)

**Comment by liversedge** [comment] 2015-11-12 16:10
dupe of #1420

**Closed** 2015-11-12 16:11 UTC
Labels: duplicate, rejected

**Comment by cleveruplink** [comment] 2015-11-12 16:18
Thanks - quickest bug triage I've ever seen! Hadn't spotted the duplicate. Wasn't able to use the command line options to turn scaling off but if I turn scaling off in Windows then everything obviously looks fine.
