### ISSUE TITLE
Provice ARM Appimage builds for Linux

### ISSUE THREAD

**Issue by piggz** [GoldenCheetah/GoldenCheetah#3773] opened 2021-01-13 12:03 UTC
Hi

Im probably in the minority here, but it might be useful to provide ARM64 appimage  builds for linux.  This would allow easy running on eg the Raspberry Pi4 or pinebook pro laptops.  I can certainly see a usecase for running golden cheetah on a pi4 with a dedicated connection to a TV.

**Comment by amtriathlon** [comment] 2021-01-13 12:26
Duplicate of #3774

**Closed by amtriathlon** 2021-01-13 12:26 UTC
