### ISSUE TITLE
Strava OAuth not working on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by p-value-sharma** [GoldenCheetah/GoldenCheetah#4377] opened 2023-07-23 02:38 UTC
Hello, I am running Ubuntu 22.04.2 LTS (64 bit). This is a relatively fresh install of Ubuntu (I've also restarted the computer twice just in case). I've downloaded GoldenCheetah v3.5 AppImage. 

I am able to open the app. However, I am unable to connect my profile with Strava. When I go to Share --> Add Cloud Accounts --> Activities --> Strava and click the Authorise button, it will open a window called OAuth, which displays nothing and appears frozen. 

Please let me know if I can provide any further information that might help debug this issue.

**Comment by amtriathlon** [comment] 2023-07-23 17:27
Likely a duplicate of #4196

**Closed by amtriathlon** 2023-07-23 17:27 UTC
