### ISSUE TITLE
Strava Sync broken

### ISSUE THREAD

**Issue by blaubein** [GoldenCheetah/GoldenCheetah#3216] opened 2019-11-16 13:00 UTC
Strava sync appears broken. New activities are not downloaded and manually running the sync tool produces an empty list. I last ran GC ca. 40 days ago, when everything was fine. Problem is present in both RC1 and v3.5-DEV1903, Linux 64-bit AppImage, running Ubuntu 19.04 (nothing changed in the OS despite regular updates but no system/distribution update).

Increasing the look-back time span produces all activities that have already been synced and tags them as "upload"; so it looks like they are not found on Strava. Running GC with option "--debug" produces: 

error "Host requires authentication"

I reauthed with Strava, removed auth, reauthed once more. No change.

**Comment by amtriathlon** [comment] 2019-11-16 13:56
This is a knew problem due to changes in Strava authorization policy, the fix is already and it will be included in v3.5 RC2 official builds.
Strava re-authorization will be necessary.
The last continuous integration build for Linux also includes the fix ant it can be downloaded from: https://transfer.sh/D4M0u/dev-prerelease-branch-master-build-3251.AppImage

**Comment by suskozaver** [comment] 2019-11-16 16:19
Any workaround for Windows? 
If not, when is RC2 scheduled? If known of course.

**Comment by jonbev** [comment] 2019-11-16 16:37
> This is a known problem due to changes in Strava authorization policy ([OAuth Updates](https://developers.strava.com/docs/oauth-updates/)), the fix is already in master and it will be included in v3.5 RC2 official builds.
> Strava re-authorization will be necessary.
> The last continuous integration build for Linux also includes the fix ant it can be downloaded from: https://transfer.sh/D4M0u/dev-prerelease-branch-master-build-3251.AppImage

Just tried and is working great, thanks.

**Comment by amtriathlon** [comment] 2019-11-16 16:59
> Any workaround for Windows?

Not that I know besides using manual upload/download.
> If not, when is RC2 scheduled? If known of course.

I will update this issue when I know.

**Comment by blaubein** [comment] 2019-11-16 23:13
Awesome, thanks a million. This works. I figured it would be yet another change in the Strava API. Wonder why this happens repeatedly. Great plus though (not sure what this is related to) is that non-public activities are being synced / downloaded. :-)

Cheers
Christian

On November 16, 2019 5:59:16 PM GMT+01:00, Alejandro Martinez <notifications@github.com> wrote:
>> Any workaround for Windows?
>
>Not that I know besides using manual upload/download.
>> If not, when is RC2 scheduled? If known of course.
>
>I will update this issue when I know.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Joshuabees** [comment] 2019-11-17 06:46
I've authenticated my Strava account with GC but when I go to Sync Activities it's blank?  WTF?  I've tried de-authorizing and re-authorizing a half-dozen times but every time I try to sync with Strava the window is blank of activities.

**Comment by Joshuabees** [comment] 2019-11-17 06:47
Windows 10 btw, just downloaded GC 3.5 tonight.

**Comment by suskozaver** [comment] 2019-11-17 07:27
A few posts before yours it clearly says, problem acknowledged, issue worked on, released not yet:
https://github.com/GoldenCheetah/GoldenCheetah/issues/3216#issuecomment-554639680

> Windows 10 btw, just downloaded GC 3.5 tonight.

**Comment by alokhan** [comment] 2019-11-17 13:00
Working on the Linux build thanks :)

**Comment by AirVetra** [comment] 2019-11-18 11:27
Waiting for the solution for Win10 as well

**Comment by ritzelrocker** [comment] 2019-11-18 18:57
The same here :-)
Many thanks in advance for your great support :-)

**Comment by NordicFlyer** [comment] 2019-11-19 15:03
Strava sync is broken. I'm looking forward to a macOS RC2 update with the fix. Thanks.

**Comment by gurtner-it** [comment] 2019-11-25 09:43
Any news?

**Comment by amtriathlon** [comment] 2019-11-25 15:51
The last continuous integration build for MacOS also includes the fix for this issue, if you want to give it a try beware this is not the same as the official build, it is generated and tested on High Sierra but it may not work on other versions. It can be downloaded from https://transfer.sh/pVgdx/dev-prerelease-branch-master-build-3271.dmg

**Comment by NordicFlyer** [comment] 2019-11-25 16:58
The developer build appears to be working on macOS Catalina 10.15.1. Thanks Alejandro.

**Comment by Joshuabees** [comment] 2019-11-25 18:51
Any updates coming for Win10?

**Comment by amtriathlon** [comment] 2019-11-25 21:11
> Any updates coming for Win10?

Current continuous integration builds for Windows don't generate an installer, if you don't build by yourself you need to wait for the next official builds and upload/download using export/import in the meantime.

**Comment by NordicFlyer** [comment] 2019-11-26 12:57
> The last continuous integration build for MacOS also includes the fix for this issue, if you want to give it a try beware this is not the same as the official build, it is generated and tested on High Sierra but it may not work on other versions. It can be downloaded from https://transfer.sh/pVgdx/dev-prerelease-branch-master-build-3271.dmg

As a separate issue, it's great to see that D2XX support is included in this build. It has been a long time since I have seen D2XX included in the official developer builds. Since SRAM bought out PowerTap the future of the PowerAgent application remains sketchy. Including D2XX support in GC allows one to contitnue to use their Joule GPS (ANT+ only) head unit for downloads. Hopefully D2XX will be included in the final build.

**Comment by richardjy** [comment] 2019-11-27 05:46
(RC1 64-bit windows) When using "Add Cloud Wizard" for either SportTracks or Strava get same error message during authorization attempt - example shown below. I assume this is part of the issue already reported and fixed in RC2. Wanted to mention that issue affects SportTracks as did not see any reference to SportTrack error in open issues. 

![image](https://user-images.githubusercontent.com/16394848/69696657-3561e100-1095-11ea-8117-f13a284edef5.png)

**Comment by amtriathlon** [comment] 2019-11-27 11:15
> Wanted to mention that issue affects SportTracks as did not see any reference to SportTrack error in open issues

No, this issue is exclusive to Strava due, to changes in their authorization scheme as described in my first response, and it affects all GC supported platforms.

What you report looks like a Windows 10 related communication issue, there is a pinned thread on users forum pointing to several useful resources to fix it: https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ

**Comment by jmanuelprada** [comment] 2019-11-27 17:34
Sorry just found this page and I having the problem of not seeing new strava activities since some weeks ago. I am using GC in windows 10 and I just installed the V3.5-RC1. 

Understood the solution is wait for the new release RC2 - is that correct ? and if so when it will be available?

cheers

**Comment by suskozaver** [comment] 2019-11-27 19:12
Correct.

When: unknown yet. 

Also waiting.

**Comment by richardjy** [comment] 2019-11-30 01:01
> 
> 
> > Wanted to mention that issue affects SportTracks as did not see any reference to SportTrack error in open issues
> 
> No, this issue is exclusive to Strava due, to changes in their authorization scheme as described in my first response, and it affects all GC supported platforms.
> 
> What you report looks like a Windows 10 related communication issue, there is a pinned thread on users forum pointing to several useful resources to fix it: https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ

Thanks for the input, Amtriathlon, and for pointing me at more GC resources. The issue was indeed computer specific. The sporttracks connection was successfully made using RC1 on a different computer (same local network but hardwired internet connection rather than wifi). 

Issue seems wifi/firewall related as the first time it was successful on the original computer was also using a hardwired connection to router. Switching back to home-wifi-only gave error again. Switching between wifi networks sometimes allows a brief period of connection, but more investigation of root cause is needed.

**Comment by desie** [comment] 2019-11-30 18:52
Hi,
I'm using git repository to compile my GoldenCheetah. Strava synchronization work fine after your fixe about the auth problem but it seems that the token is only temporary obtained. 
For example I create the synchronization account in the option tab at the beginning of the day. Synchro work fine from and to Strava, and at the end of the day when I try to synchro it doesn't work anymore.

**Comment by amtriathlon** [comment] 2019-11-30 20:40
@desie this was the behavior after my first commit (ab18468a98e9240a82ae77c83d757d5f058e8469) since the new tokens are temporary (around 6hr according to docs), the renewal part was included in the second commit (https://github.com/GoldenCheetah/GoldenCheetah/commit/bef37ea49caf574c86e050608120cf6e731f4ff6), it is better explained and documented in the original issue (#3199)

**Comment by Ramoonus** [comment] 2019-12-01 10:11
for me this issue sorted out itself using RC1

**Comment by ritzelrocker** [comment] 2019-12-02 10:09
I've switched to todays plan free account to have the sync working again. Works fine for me & I'm rid of the strange Strava thinks.
:-)

**Comment by AirVetra** [comment] 2019-12-02 12:31
For me nothing changed in RC1 (win10)

**Comment by Kirsty99** [comment] 2019-12-02 13:36
Uploads training fine to Strava, Windows 10 RC1 but dose not download

**Comment by pbanders** [comment] 2019-12-02 16:35
Running RC1 Win10. Reauthorized successfully, sync still broken with Strava. Closed, reopened, sync still broken.

**Comment by amtriathlon** [comment] 2019-12-02 21:19
>Running RC1 Win10. Reauthorized successfully, sync still broken with Strava. Closed, reopened, sync still broken.

Yes, it is a known issue, the fix is in master code, and it will be available in RC2.

**Comment by pbanders** [comment] 2019-12-02 21:24
> > Running RC1 Win10. Reauthorized successfully, sync still broken with Strava. Closed, reopened, sync still broken.
> 
> Yes, it is a known issue, the fix is in master code, and it will be available in RC2.

Thanks, my comment was in response to those who posted above that RC1 was working for them now in Win10, it's still broken for me. Until then, I'm just manually uploading rides. Thanks again for all the hard work that's gone into GC over the years, much appreciated.

**Comment by jonbev** [comment] 2019-12-03 15:03
Is there a dev build of every commit to master? I can't see a link on Travis?

**Comment by amtriathlon** [comment] 2019-12-03 16:04
>Is there a dev build of every commit to master? I can't see a link on Travis?

Yes, there are 2 builds on travis for each commit to master: MacOS and Linux, if you go to the end of the log for the platform you want and expand the after_success script output, you will find the upload to transfer.sh, which returns the link for download.

**Comment by jonbev** [comment] 2019-12-03 16:13
Awesome, thanks.

I didn't notice that the log lines were hidden, sorry.

**Comment by db369** [comment] 2019-12-04 21:01
Where can I find the latest AppImage? 3251 doesn't seem to be available on transfer.sh any more. Thanks!

**Comment by jonbev** [comment] 2019-12-04 21:23
https://transfer.sh/Kc3HF/dev-prerelease-branch-master-build-3285.AppImage

**Comment by amtriathlon** [comment] 2019-12-06 16:08
Windows installer for v3.5 RC2 are available for download at https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC2, they should fix this issue once you reauthorize with Strava.

**Comment by amtriathlon** [comment] 2019-12-09 11:10
Until the official RC2X build for Mac is available the automatically generated one can be downloaded from: https://transfer.sh/sKSxD/dev-prerelease-branch-master-build-3309.dmg

**Closed by amtriathlon** 2019-12-09 11:10 UTC
Labels: Fixed already, cloud

**Comment by Ramoonus** [comment] 2019-12-17 16:49
problem occouring to me again today using RC2x

**Comment by amtriathlon** [comment] 2019-12-17 17:03
> problem occouring to me again today using RC2x

This is unlikely, this issue was due to a change in Strava OAuth.
Just checked and it is working for me now, if you are on Windows please check the pinned thread at the users forum:  https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ

**Comment by Ramoonus** [comment] 2019-12-17 17:22
not login but sync isnt working properly

**Comment by amtriathlon** [comment] 2019-12-17 19:10
Sync is what I tested, it is working for me.
