### ISSUE TITLE
[Request for Future] Make file import process multithreaded

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1495] opened 2015-08-06 19:10 UTC
Now import 1 years activity it's too long time process, but only 1 of 8 CPU kernel used.

Good practice - to use 75-80% of the total number of cores (if it >1).

**Comment by liversedge** [comment] 2015-08-06 20:03
We use a map/reduce for the metrics refresh, which uses all cores, hard.
Import large number is a one off edge case that is not worth the complication and the UI would be confusing since it is validating each ride as you go.

**Comment by mtbkeith** [comment] 2015-08-06 20:18
A few months back I had written a multi-threaded approach to the import -
using multiple cores. I can dig it up at least for a review.

Thanks,
Keith

**Comment by liversedge** [comment] 2015-08-06 20:19
OK :)

Be interesting to see how you approached the gui update !

Mark

**Comment by liversedge** [comment] 2015-12-06 12:30
duplicate of #1527

**Closed by liversedge** 2015-12-06 12:30 UTC
Labels: P3, performance
