### ISSUE TITLE
Joule GPS download fail

### ISSUE THREAD

**Issue by laurjohn** [GoldenCheetah/GoldenCheetah#1357] opened 2015-04-05 23:31 UTC
Hi,

I have a Joule GPS  v 19.087 which until recently (3/31) would download fine with GC. However since Apr 1, the download will progress through Joule GPS identified/Read ride summary then consistently fails with this error.

", read only 2960 bytes instead of: 3080"

Is there any way I can download the data off the device???

thanks,

Laura

**Comment by urby69** [comment] 2015-04-14 14:19
Hi there, I am sorry to use your issue but I feel I don't to open a new one since it is somehow connected to yours. I never had any issue downloading the data, but the problem is that I cannot find where the data is downladed to.  This is what I get:
getting summary ...
getting data ...
Get Unit Software Version...
Version19.087 (8)
Get System info...
Joule GPS identified
Read ride summary...
1 detailed rides
download completed successfully
But no file to find. WHat am I missing?
Thanks and sorry again, Milan

**Comment by liversedge** [comment] 2015-05-22 08:18
The problem is fixed in v3.2, which will be released soon, or via dev builds

**Closed by liversedge** 2015-05-22 08:18 UTC

**Comment by urby69** [comment] 2015-11-05 20:40
The problem is the same even in 3.2. I saw you closed the thread so I hope
this message will get to you.

2015-05-22 10:18 GMT+02:00 Mark Liversedge <notifications@github.com>:

> Closed #1357 <https://github.com/GoldenCheetah/GoldenCheetah/issues/1357>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1357#event-311456985>
> .
>



-- 
lp
milan
