### ISSUE TITLE
Fix Elevation Errors - Free Monthly Free Plan Limit Exceeded

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3789] opened 2021-01-19 16:25 UTC
Error: 
![image](https://user-images.githubusercontent.com/56834737/105062081-1d57d880-5a72-11eb-9bfc-6dcd2554d0a7.png)

Actions: Edit -> Fix elevation Error -> OK

Version 3.6 Dev
Build: January 2021

Please advise for fix or workaround? Thanks

**Comment by amtriathlon** [comment] 2021-01-19 17:25
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2780

> Please advise for fix or workaround?

Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Closed by amtriathlon** 2021-01-19 17:25 UTC
Labels: duplicate

**Comment by GuyMelville** [comment] 2021-02-01 14:57
Hi,

How are you?

I agree that this is not a bug, but it remains an issue. if users can't use the feature after 1430 GMT on the 1st of the month due to uptake of the monthly allowance, the feature is redundant.

Is it within the license agreement for you to set up so that users can enter their own license key so that they can use their allowance from their own license and not the Golden Cheetah Developer license?

Best regards,

Guy

**Comment by amtriathlon** [comment] 2021-02-01 15:45
We use the issue tracker to track issues and features and we have 2 forums (users and developers) for questions and discussions, please use them, it should be not that hard to understand.
