### ISSUE TITLE
Running Speed and Swim Speed in training trend in km/h, need in pace min/km for "Run" or min/100m for "Swim"

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2062] opened 2016-08-24 06:11 UTC
[http://velo100.ru/files/GC-UI-01-pace.png](http://velo100.ru/files/GC-UI-01-pace.png)
1. Activity is "Run"
2. On speed trend i see speed in km/h. This good for Cycling activites or  any other if this not Run or Swim. **Not OK**. For "Run" i need see speed in pace "min/km", for "Swim" in "min/100m"
3. On popup i see both speed and pace - **this OK**.

**Comment by amtriathlon** [comment] 2019-11-01 14:51
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/1418

**Closed by amtriathlon** 2019-11-01 14:51 UTC
Labels: duplicate
