### ISSUE TITLE
'Rides' list scrolls to beginning every time it refreshes instead of keeping current scroll position.

### ISSUE THREAD

**Issue by ebrandt** [GoldenCheetah/GoldenCheetah#1055] opened 2014-09-09 13:39 UTC
Use case:
I have ~1100 rides in GC. I have the 'Rides' control visible in the left pane. I select a ride from it, perhaps in the middle, perhaps at the end of the list. I modify something about the ride. I then Activity->Save Ride. The 'Rides' control updates itself and the scroll is set to show the first ride in the list, rather than the current ride. Now I need to re-scroll through that list to find the ride I was looking at. If it's the last ride, this is easy with the 'end' key, but if it is not the last ride, then it can be a chore. 

Keeping the currently selected ride within the scroll's view when the Rides list is refreshed would be much more convenient.

**Comment by amtriathlon** [comment] 2019-04-10 14:07
I can't reproduce this on current v3.5dev, I think it is fixed, can we close this?

**Comment by liversedge** [comment] 2019-04-10 15:14
I think so, it introduced the regression regarding refreshes.

**Comment by amtriathlon** [comment] 2019-04-10 20:15
Ok. Let's close this and open another one for the refresh problem

**Closed by amtriathlon** 2019-04-10 20:15 UTC
Labels: P2, UX
