### ISSUE TITLE
Strava auto import does not download all activities

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#4385] opened 2023-08-14 10:53 UTC
I posted this issue recently, I am posting again because it seems to have been closed incorrectly. 

I use Strava to download my activities, and have auto-import enabled during startup. However, it does not download all my activities, **_even if these activites are all from the last 30 days_**.

For example, I recently opened GC after two weeks of not using it. About half of the new activities where downloaded.
- I can keep pressing the 'sync' button in lower left corner, and every time more activities will appear until complete
- Using the download function from the top menu always downloads all activities (but requires more manual steps)

Please let me know if I can provide more input.

**Comment by amtriathlon** [comment] 2023-08-14 20:09
Duplicate of #4376, we have a users forum for discussions.

**Closed by amtriathlon** 2023-08-14 20:09 UTC
Labels: duplicate, Forum Question
