### ISSUE TITLE
Support different bikes / equipment

### ISSUE THREAD

**Issue by UlysseUlysse** [GoldenCheetah/GoldenCheetah#2481] opened 2017-04-27 06:57 UTC
Hi Mark, why don't envisage doing several size of whells  such as for example on for an Mountainbike and a other for road bike, Best regards Paul

**Comment by liversedge** [comment] 2017-04-27 08:07
This  is a duplicate of #1572

**Closed by liversedge** 2017-04-27 08:07 UTC
Labels: configuration, duplicate

**Comment by UlysseUlysse** [comment] 2017-04-27 12:36
Sorry I d'ont speak English, thank you for the link

**Comment by liversedge** [comment] 2017-04-27 12:36
No worries !
