### ISSUE TITLE
fenix 3 to strava fine,strava to GC 3.5 dev not so

### ISSUE THREAD

**Issue by johnnyboy4711** [GoldenCheetah/GoldenCheetah#3029] opened 2019-02-22 22:09 UTC
3.5 Dev 32bit pulling workouts from specific dates from strava  into GC but no data in each workout.
only started since i have been using fenix 3 in garmin connect  last couple of weeks.

**Comment by johnnyboy4711** [comment] 2019-02-22 22:10
![image](https://user-images.githubusercontent.com/10092064/53274275-9ca9c980-36ee-11e9-85ab-232d9d099b8e.png)

**Comment by MaksVasilev** [comment] 2019-02-22 22:12
Try new build with fixed Strava erorr:
https://github.com/GoldenCheetah/GoldenCheetah/releases

сб, 23 февр. 2019 г. в 01:10, johnnyboy4711 <notifications@github.com>:

**Comment by johnnyboy4711** [comment] 2019-02-22 22:19
cheers!appreciate it!

**Comment by johnnyboy4711** [comment] 2019-02-22 22:21
still the same

**Comment by johnnyboy4711** [comment] 2019-02-22 22:23
only way of importing is to manually DL from strava and upload into GC

**Comment by johnnyboy4711** [comment] 2019-02-22 22:25
![image](https://user-images.githubusercontent.com/10092064/53274871-cfed5800-36f0-11e9-9584-3363d63ca3a4.png)

**Comment by johnnyboy4711** [comment] 2019-02-22 22:27
![image](https://user-images.githubusercontent.com/10092064/53274930-04f9aa80-36f1-11e9-880a-ca34ea281d64.png)

**Comment by MarkRebuck** [comment] 2019-02-23 16:21
This is a duplicate of  https://github.com/GoldenCheetah/GoldenCheetah/issues/3019 , which already has a patch ad will be fixed in the next development build.

**Comment by danjjl** [comment] 2019-02-25 08:53
I am having the same bug with a Garmin Edge 520 on both the October dev build and the January dev build (1901).

This bug happens both on macOS and on Linux.

It is specific to rides with my Garmin.

Rides from an Elite smart trainer → Strava → golden cheetah work fine.

Any useful information I could collect to help debug this bug?

**Comment by Ramoonus** [comment] 2019-02-25 17:44
same here, i guess it has nothing to do with the fenix device
but in general strava - GC

**Comment by albertmink** [comment] 2019-02-25 18:25
I slightly disagree. All of a sudden, we all got empty activities through strava-GC syncronisation. For me, the february build fixed this issue.

Ref:
![unbenannt](https://user-images.githubusercontent.com/38354196/53359157-6f4d5d80-3932-11e9-831d-15bbaebf132a.JPG)

**Comment by johnnyboy4711** [comment] 2019-02-25 19:18
may have something to do with garmin express

**Comment by danjjl** [comment] 2019-02-26 09:03
I could reproduce the issue on builds October 2018, January 2019.

- I **do not** experience this bug with activities synced from Zwift → Strava → Golden Cheetah
- I do experience the bug with activities synced from Garmin Express (Windows PC) → Strava → Golden Cheetah
- I also experience the bug with activities synced from Garmin Connect (Android) → Strava → Golden Cheetah

Downloading an "empty" activity `.gpx` file from Strava and manually importing in Golden Cheetah works fine.

**Comment by RoberRober** [comment] 2019-03-01 12:35
I have the same problem with Polar-Strava-GoldenCheetah syncronizations. I´m working with V3.4 and I have tried with v3.5-DEV1810 and I can see activities until February 13rd, but not more recent.

**Comment by Joern-R** [comment] 2019-03-01 12:57
Basically everybody who moved to the new 1903 DEV Build reported the Strava (no data in download) problem to be fixed and own testing showed the same. There is no indication that there are problems with specific devices - especially since Strava has there own download stream approach (and does not forward the original .FIT file to the downstream receiver.) Thus a device specific problem pretty unlikely. 

Please make sure to have the latest version in place - and delete the activities without data before synchronizing.

For further feedback please use the forum:

https://groups.google.com/forum/?hl=de#!forum/golden-cheetah-users

and for the 1903 Build the specific feedback thread:

https://groups.google.com/d/msg/golden-cheetah-users/iiesNbpiqYw/DXKzC1vgBAAJ

**Closed by Joern-R** 2019-03-01 12:57 UTC

**Comment by RoberRober** [comment] 2019-03-01 13:16
Thanks!
