### ISSUE TITLE
Import from file crash

### ISSUE THREAD

**Issue by sangogi** [GoldenCheetah/GoldenCheetah#1248] opened 2015-01-14 14:22 UTC
Hi~

I have a problem.
I use Powertap and Edge 800.
Win7 and GC verion is last version.

Version Info

Build date: Aug 17 2014 23:59:06
Build id: 3100
Version: 3.1.0
DB Schema: 80
Metrics: 133
OS: Win
QT	4.8.6
QWT	6.1.1
GCC	4.9.0
SRMIO	0.1.1~git1 e84852a
OAUTH	1.0.3
D2XX	yes
QWTPLOT3D	0.2.6
KML	none
ICAL	1.0
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
LUCENE	2.3.3.4
VIDEO	vlc

My data is import error, only '2014/10/01 ~ 2014/12/31'

All data is good in WKO+, but GC is bad.

![image](https://cloud.githubusercontent.com/assets/4444700/5740155/234f4fea-9c44-11e4-979f-a96f4b6e4dc3.png)

![image](https://cloud.githubusercontent.com/assets/4444700/5740050/530b4ba4-9c43-11e4-8913-0119764080da.png)

Import error data filename is changed '-4713_xxx_xxx'

![image](https://cloud.githubusercontent.com/assets/4444700/5740045/42430e4c-9c43-11e4-8b14-27c7086abd56.png)

For help.

Thanks.

**Comment by liversedge** [comment] 2015-01-14 14:43
Hi the date parsed incorrectly on the files with -4713
Can you share one of the wko or fit files with this bad date so we can have a look ?

**Comment by sangogi** [comment] 2015-01-14 14:52
Error File Download link
https://drive.google.com/file/d/0B8ngShBILSF1aDUwWVlrRXo4VlU/view?usp=sharing

**Comment by liversedge** [comment] 2015-01-14 15:54
I imported these files without issues ---- but, and this is important --- *the filename needs to be changed* before you import --  as we override the date contained in the file and use the date inferred by the filename, but only if the filename matches  yy_mm_dd_xx_xx_xx_xx format.

**Comment by sangogi** [comment] 2015-01-15 01:27
1. PWO(WKO+ data file) and fit(Edge 800 data file) : GC Import error(Period : 2014/10/01~2014/12/31)
2.  Changed file name data files is same error(-4713)
ex) SangOk_Lee_2014_10_04_09_46_43.wko -> 2014_10_04_09_46_43.wko
3. Direct files copy in GC data folder(C:\Users\solee\AppData\Local\GoldenCheetah\SangOGi) : No error
3-1. Changed file name
3-2. Import data file(GC - Import form file) : Same import error -4713(Period : 2014/10/01~2014/12/31)
3-3. Delete error files(-4713_xx_xx_xx_xx_xx.wko/cpx) in GC data folder
3-4. Direct COPY data files(3-1 changed file) in GC data folder
3-5. GC run and OK

![image](https://cloud.githubusercontent.com/assets/4444700/5750991/484bc40c-9ca0-11e4-8f50-081d5f82678d.png)

**Comment by liversedge** [comment] 2015-01-18 12:59
Closing as this is not a bug -- the filenames are causing the problem and should be changed.

**Closed by liversedge** 2015-01-18 12:59 UTC
