### ISSUE TITLE
Open GC forces Mac to crash

### ISSUE THREAD

**Issue by docsport77** [GoldenCheetah/GoldenCheetah#4390] opened 2023-08-29 11:14 UTC
Opening GC forces two of my Macs to crash, meaning they went dark and you have to login again, start everything new and restore some setting (external monitor for example).

With the latest stable version it seems to get better on one machine meaning sometimes it starts after 30s you cannot do anything without crashing.

![Bildschirmfoto 2023-08-29 um 13 10 03](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/c7c581cc-8668-4b35-ab27-4b637da36bc3)

![Bildschirmfoto 2023-08-29 um 13 10 41](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/6f1aa83a-2ce0-4067-95e3-db2247ccc684)

One Mac has the Nolio version too and this one works without any problems.

**Comment by amtriathlon** [comment] 2023-09-07 11:47
Duplicate of #4379

**Closed by amtriathlon** 2023-09-07 11:47 UTC
Labels: duplicate, Forum Question
