### ISSUE TITLE
Adjust timescale in compare view

### ISSUE THREAD

**Issue by bjarnibi** [GoldenCheetah/GoldenCheetah#1823] opened 2016-01-31 17:33 UTC
Feature request:   When viewing two or more activities/intervals in the compare view, it would be very useful to be able to adjust the timeline to slide/shift activities left or right on the timeline to be able to align the intervals or sections being compared.

Most of the time intervals or sections being compared from different activities occur at different times in each ride and are displayed shifted relative to each other when being compared.

**Comment by amtriathlon** [comment] 2020-11-24 12:46
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/1178

**Closed by amtriathlon** 2020-11-24 12:46 UTC
Labels: P2, UX
