### ISSUE TITLE
Please add a marker on map when hovering mouse over full plot graph on Map view

### ISSUE THREAD

**Issue by mtutin** [GoldenCheetah/GoldenCheetah#2497] opened 2017-04-30 15:07 UTC
Could you please add a marker on map when hovering mouse over full plot chart? It would be also very useful to be able to highlight regions on the graph and be able to create new interval there. Something similar to Strava's 'Analysis' view.
Ideally it would be great to combine Map and Ride views on the same screen.

**Comment by liversedge** [comment] 2017-05-07 09:57
You can create intervals on the map.
There is a small plot on the map settings.

**Comment by mtutin** [comment] 2017-05-14 11:43
Is it recently added? I use version 3.4 on Windows. If I try to select part of the track on the map (OSM layer), the map just moves around. If I try to select something on the small plot at the bottom, nothing happens.
I can create an interval on other timeline views, but it is very hard to set the range associated with specific landmarks (e.g. from 'intersection A' to 'city B'). Such intervals are convenient for detailed segment analysis.

**Comment by grauser** [comment] 2017-05-14 13:58
Use CTRL+click

**Comment by slcpunk** [comment] 2020-06-24 16:10
Also wanting this.  Impossible to accurately select a segment using just the map.  If you zoom in close enough, then both ends of segment won't be visible, and if you zoom out then can't accurately select the track.  ( once zoomed in and selecting, can't move off the screen )  As suggested, being able to select off the chart would solve the issue.  I tried CTRL+click, alt/shift ... nothing.

OS Linux.  Version 3.5-DEV1810

TIA

**Comment by amtriathlon** [comment] 2020-06-24 17:47
> OS Linux. Version 3.5-DEV1810

This is an old development version, please use one of our published versions from http://www.goldencheetah.org/

**Comment by amtriathlon** [comment] 2020-06-24 17:57
I am closing this since it refers to older versions previous to this relevant change: https://github.com/GoldenCheetah/GoldenCheetah/commit/ca9b5b27bbaba51da3d06faf35ad2f20f5fe94a9, currently when the cursor hovers the route it changes to indicate click and drag over the route will select and interval instead panning the map.

**Closed by amtriathlon** 2020-06-24 17:57 UTC
Labels: P2, gui / workflow request

**Comment by slcpunk** [comment] 2020-06-24 18:47
Thanks.  Upgraded to build ID 3991  ( latest non dev build ).  Still seems the same, but I think we're not talking about the same functionality.  The issue is that it is impossible to select a segment that doesn't fit on the map.  I have to zoom in to see the track, but then the entire segment is not visible.  While creating a selection, there is no way to pan the map.  The better way to do it would be use the chart at the bottom to select the segment and have the map _show the selection as it was drawn_  attached image, not sure if it will help, but segment goes off the screen to the right.  I can't select the entire thing.  Work around is to "edit interval" and change the end time manually.  
![Selection_090](https://user-images.githubusercontent.com/5738127/85615063-e3783e00-b618-11ea-8cf0-f0b6edd081f9.png)
![Selection_089](https://user-images.githubusercontent.com/5738127/85615072-e5420180-b618-11ea-9a81-073ea94e82ac.png)

**Comment by amtriathlon** [comment] 2020-06-24 19:04
Currently you can do that in Tiled mode, see https://github.com/GoldenCheetah/GoldenCheetah/issues/2687, this likely will change in v3.6

**Comment by DrNipples** [comment] 2020-08-02 11:42
I also think it would be nice to hover and see single-point data or to highlight parts of a track with a different mouse button to see the data without creating a segment which has to be deleted afterwards.
