### ISSUE TITLE
Switch between several layouts

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#1631] opened 2015-11-07 10:36 UTC
Maybe using hotkey or menu entry:
Manage and switch between severay overlays widgets layout
(XML layout configuration file already have ability to contain several layout but it is not used)

**Comment by liversedge** [comment] 2015-12-06 12:22
duplicate of #642

**Closed by liversedge** 2015-12-06 12:22 UTC
