### ISSUE TITLE
Power curve of Elite Turbo Muin

### ISSUE THREAD

**Issue by Jee-O** [GoldenCheetah/GoldenCheetah#1223] opened 2015-01-06 14:52 UTC
Can the power curve of the Elite Turbo Muin be added. I found this formula on the internet.
p = 0.00791667 v^3 + 0.125 v^2 - 0.16669 v - based on 110W@20k, 700W@40k, 2150W@60k
I would really appreciate it, so I can use Golden Cheetah for my indoor training,

**Comment by liversedge** [comment] 2015-01-06 15:13
Sure thing. Should be fairly easy. Can you let me know the source you used for those coefficients ?

**Comment by Jee-O** [comment] 2015-01-06 15:18
https://www.facebook.com/TrainerRd/posts/557725977631380 
It's in one of the reactions. He did a fit in excel from 3 data points given by the manufacturer Elite.
The power curve on this site looks the same, I think: http://www.powercurvesensor.com/cycling-trainer-power-curves/

**Comment by liversedge** [comment] 2015-01-19 20:33
closing as a dupe of #1075

**Closed** 2015-01-19 20:33 UTC
Labels: device support request, duplicate, P1
