### ISSUE TITLE
Bluetooth not working on macOS v 12.0.1

### ISSUE THREAD

**Issue by erikboto** [GoldenCheetah/GoldenCheetah#4093] opened 2021-12-02 15:35 UTC
I'm not entirely sure, but I think this is related to macOS 12 (Monterey). If someone could confirm that e.g. the newest dev-release work with BLE devices on older macOS that would be nice.

The scanning for BLE devices do not work. If I start the app with --debug I see the following lines repeating when trying to connect to a bluetooth device in Train View:
`qt.bluetooth.osx: IOKit error code:  1
Error while scanning BT devices: QBluetoothDeviceDiscoveryAgent::UnknownError`

Possibly related to this issue in the Qt Issue Tracker: https://bugreports.qt.io/browse/QTBUG-96557

**Comment by erikboto** [comment] 2021-12-10 07:52
I tried to add the `NSBluetoothAlwaysUsageDescription` key to the .plist file, and gave `GoldenCheetah` permissions to access bluetooth in the macOS security and privacy settings, but still no luck. A bit annoying since adding that to the .plist for Qt's HeartRate Game-example fixed that app, so I really thought that would do the trick even for GoldenCheetah. One difference was that I built GC using Travis-CI and the HeartRate Game was built locally.

Apparently there's also a difference now in macOS if you run the binary inside the bundle, or if you launch the bundle itself. Launching the binary via the command line, like when passing --debug to enable debug output, will apparently now use the .plist file and therefore the app won't get access to things granted in that file.

**Comment by amtriathlon** [comment] 2021-12-10 23:07
> I tried to add the `NSBluetoothAlwaysUsageDescription` key to the .plist file, and gave `GoldenCheetah` permissions to access bluetooth in the macOS security and privacy settings, but still no luck. A bit annoying since adding that to the .plist for Qt's HeartRate Game-example fixed that app, so I really thought that would do the trick even for GoldenCheetah. One difference was that I built GC using Travis-CI and the HeartRate Game was built locally.

Travis-CI macOS builds get the plist from https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Resources/mac/Info.plist.app

> Apparently there's also a difference now in macOS if you run the binary inside the bundle, or if you launch the bundle itself. Launching the binary via the command line, like when passing --debug to enable debug output, will apparently now use the .plist file and therefore the app won't get access to things granted in that file.

Does this difference also happens if you use the macOS open command to pass parameters like in https://github.com/GoldenCheetah/GoldenCheetah/wiki/Disable-R-Or-Python?

**Comment by erikboto** [comment] 2021-12-13 04:55
> > I tried to add the `NSBluetoothAlwaysUsageDescription` key to the .plist file, and gave `GoldenCheetah` permissions to access bluetooth in the macOS security and privacy settings, but still no luck. A bit annoying since adding that to the .plist for Qt's HeartRate Game-example fixed that app, so I really thought that would do the trick even for GoldenCheetah. One difference was that I built GC using Travis-CI and the HeartRate Game was built locally.
> 
> Travis-CI macOS builds get the plist from https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Resources/mac/Info.plist.app

Yes that is the file I tried changing. Here's the branch I was trying out.

> 
> > Apparently there's also a difference now in macOS if you run the binary inside the bundle, or if you launch the bundle itself. Launching the binary via the command line, like when passing --debug to enable debug output, will apparently now use the .plist file and therefore the app won't get access to things granted in that file.
> 
> Does this difference also happens if you use the macOS open command to pass parameters like in https://github.com/GoldenCheetah/GoldenCheetah/wiki/Disable-R-Or-Python?

Oh, I did not now about that was of passing args (I'm far from a mac power user). I will test that and report back.

**Comment by erikboto** [comment] 2021-12-13 13:00
Passing args via the open call means that the plist file is used as it should. I verified it using the heartrate-game example which works ok if started with `open heartrate-game.app` but not when pointing to the executable inside heartrate-game.app/ .

**Comment by liversedge** [comment] 2021-12-13 13:24
Have you tried this:
https://nethack.ch/2014/03/30/quick-tip-flush-os-x-mavericks-plist-file-cache/

**Comment by erikboto** [comment] 2021-12-13 15:06
> Have you tried this: https://nethack.ch/2014/03/30/quick-tip-flush-os-x-mavericks-plist-file-cache/

I did now, and it didn't have any effect. I noticed that the heartrate-game example also has LSMinimumSystemVersion = "10.13" set in Info.plist, but I can't see that it should make any difference.

It's cumbersome to experiment too, because if I manually edit the Info.plist in GoldenCheetah.app it goes bananas with weird errors during startup (which disappears again if I restore the original). So I have to trigger a build via travis-ci to get a bundle to test with. I wonder if it's some kind of tampering check on the plist or something, but that's just pure speculation on my side.

**Comment by amtriathlon** [comment] 2022-12-28 13:04
Snapshot build still fails after https://github.com/GoldenCheetah/GoldenCheetah/commit/dfeb8532a995e130a699c5910805c200d29b5e61, allowing GoldenCheetah access to Bluetooth in macOS config only changes the error message.

**Comment by nharperbkk** [comment] 2023-04-09 08:12
Good day, is there any progress or approach for resolving this?  Keep looking at new builds but none permitting OSX machines to see bluetooth devices.

thank you.

**Comment by amtriathlon** [comment] 2023-04-09 21:41
> is there any progress or approach for resolving this?

We accept patches.

**Comment by enngq11k** [comment] 2023-12-17 19:30
I finally got a macOS build running on my machine (Air M1, macOS 14.2). Really fast build times :)

Bluetooth search did not work with 3.6.0 and with the current Snapshot Release. But my own build did succeed. I also received the Bluetooth access request with all versions, so I wasn't able to reproduce this problem.

Result:
Search was successful, but I found some devices without a name. I think they are the same devices I found with the Linux build. I think we can just remove them from the list.
<img width="600" alt="gc-local-bt-device" src="https://github.com/GoldenCheetah/GoldenCheetah/assets/148800743/d424025d-dd34-496a-b587-301236cd2f57">



Differences to the Snapshot Release:
<img width="1500" alt="gc-versions" src="https://github.com/GoldenCheetah/GoldenCheetah/assets/148800743/d8df6434-4916-47f5-89d7-6884e175a747">

- Compiled for Apple silicon
- QT 5.15.10 instead of 5.15.6

Changes to get a build:
- gcconfig.pri
  - QMAKE_CXXFLAGS += -mmacosx-version-min=10.7 -D_Noreturn=
  - QMAKE_CFLAGS_RELEASE += -mmacosx-version-min=10.7
  - QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15
- src.pro
   - CONFIG += c++17 instead of c++11
- /contrib/levmar/compiler.h
   - #define LM_FINITE isfinite instead of #define LM_FINITE finite
 
 
Log of the local release build:
```
[19:49:19.324] warning: Populating font family aliases took 52 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
[19:49:19.745] warning: Window position QRect(2660,880 5000x1180) outside any known screen, using primary screen
OpenData disabled, secret not defined.
2023-12-17 19:49:26.155 GoldenCheetah[3483:68258] -[IOBluetoothDeviceInquiry initWithDelegate:] -  0x6000030d1440
2023-12-17 19:49:26.520 GoldenCheetah[3483:68258] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
[19:49:42.671] warning: Manually interrupting IOBluetoothDeviceInquiry
[19:50:07.691] debug: BT scan finished
```

**Also interesting:** GC was way more responsive with the native Apple Silicon Build. Usually Rosetta2 is quite fast, but this was a big difference.

**Comment by erikboto** [comment] 2023-12-18 13:02
So maybe there is hope! Could you share some more details on your Qt installation, did you build Qt 5.15.10 yourself or is there working binaries somewhere? Or do you have Qt Commerical?

**Comment by enngq11k** [comment] 2023-12-18 19:24
I'm just using homebrew.
https://formulae.brew.sh/formula/qt@5

Works fine in the terminal, but if you need an IDE you can also install QT Creator.
https://formulae.brew.sh/cask/qt-creator

**Comment by amtriathlon** [comment] 2023-12-19 14:37
Thank you for testing!

> Differences to the Snapshot Release:
> * Compiled for Apple silicon
> * QT 5.15.10 instead of 5.15.6
> 
> Changes to get a build:
> 
> * gcconfig.pri
>   
>   * QMAKE_CXXFLAGS += -mmacosx-version-min=10.7 -D_Noreturn=
>   * QMAKE_CFLAGS_RELEASE += -mmacosx-version-min=10.7
>   * QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15
> * src.pro
>   
>   * CONFIG += c++17 instead of c++11
> * /contrib/levmar/compiler.h
>   
>   * #define LM_FINITE isfinite instead of #define LM_FINITE finite

So candidates fixes would be:

1. add QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15 to gcconfig.pro, the easiest one to try
2. change to QT 5.15.10 from 5.15.6, theoretically easy since enabling brew updates should provoke this, more complex in practice since the time constraints for Travis-ci builds.
3. Cross compile for Apple silicon, if the problem is caused by Rosetta2...

**Comment by erikboto** [comment] 2023-12-22 14:14
I just tested out building with Qt 5.15.11 and the modifications mentioned above, and it works for me both when I build for arm64 and x86_64. So this looks very promising! I've only tried scanning and verifying that I get some results, but if it gets that far I suspect the rest should work fine too.

**Comment by amtriathlon** [comment] 2024-01-07 20:07
Latest snapshot build works on Ventura 13.6, including selective sensor pairing, fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/31636b196d5cb7bab0595f420697511672872a63

**Closed by amtriathlon** 2024-01-07 20:07 UTC
Labels: platform support error, P2
