### ISSUE TITLE
DISTANCE appears to have 'backward' steps

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#2446] opened 2017-04-11 06:35 UTC
Best described with examples:
![screen shot 2017-04-11 at 07 30 08](https://cloud.githubusercontent.com/assets/11195133/24895595/34daa858-1e89-11e7-9b0f-63290675af72.png)
And the .fit file when viewed in EDIT screen actually self-highlights the backward step in DISTANCE:
![screen shot 2017-04-11 at 07 31 14](https://cloud.githubusercontent.com/assets/11195133/24895607/41c4fe42-1e89-11e7-8e7d-18de06b6944d.png)

So, excuse my ignorance , is the data in the .fit file the 'raw' recorded data - in which case I assume it is NOT a GC issue, but a recording issue?

**Comment by RJKflyer** [comment] 2017-04-11 08:59
Looks like a problem generated by the Wahoo ELEMNT - am logging with them. However, interested in any views from the experts here.

**Comment by liversedge** [comment] 2017-04-11 09:26
Yeah, distance going backwards is wrong. It might be our FIT file reader, so have you tried on any other software?

Keep us updated with info as you get it ?

CHEERS
Mark

**Comment by RJKflyer** [comment] 2017-04-12 06:21
UPDATE: the 'reverse' glitch is just visible in RwGPS so confirms not a GC issue - aside GC, I don't use any other standalone s/w. 

Wahoo Beta now investigating the FIT file writer. Will keep you posted.

**Comment by liversedge** [comment] 2017-05-07 10:03
Closing as not a bug in GC.

**Closed by liversedge** 2017-05-07 10:03 UTC
Labels: under review

**Comment by RJKflyer** [comment] 2017-05-07 11:53
Confirmed as bug in ELEMNT software, now being resolved.
