### ISSUE TITLE
Importing Zwift FIT Files Gives Incorrect Timestamps

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2704] opened 2017-11-21 15:44 UTC
Importing a FIT file from a Zwift workout results in the the date and time being incorrectly detected as seen in the attached screen shot.

I have also attached the FIT file used to create this screenshot. The correct timestamp GMT for this file is 2017-11-15 at 15:52 (as can be seen in the filename). Note that I had to add a .txt extension to the file to get GitHub to accept it as an attachment.

I'd happily see if I can get to the bottom of this if someone could give me a pointer to the file/lines that contain the import code / date parsing. Perhaps is a timezone issue?!

![screen shot 2017-11-21 at 15 34 25](https://user-images.githubusercontent.com/804578/33081668-bc7fe094-ced2-11e7-8a9d-99eedf7ab007.png)

[2017-11-19-15-52-45.fit.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1491964/2017-11-19-15-52-45.fit.txt)

**Comment by amtriathlon** [comment] 2017-11-21 16:01
I think this is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2669

**Closed by amtriathlon** 2017-11-21 16:01 UTC
Labels: duplicate
