### ISSUE TITLE
Unable to highlight all intervals at once on v3.3

### ISSUE THREAD

**Issue by 3dflyer87** [GoldenCheetah/GoldenCheetah#1743] opened 2015-12-23 18:08 UTC
Hey all,

I tried out v3.3, but found out that there is no longer the ability to highlight all intervals at once on charts such as the power or heart rate histogram.  This was a very useful feature in v3.1.  An example is if you have 4 intervals, you could select all 4 of them and they would highlight in the power distribution histogram, and at the same time if you hovered over one of the intervals on the left hand side of the screen, it would highlight just that interval.  Thus, in this example, you would see the power distribution for the entire ride, all of the the work intervals, and the single interval in question, all at the same time.  This is infinitely useful for effort comparisons.  If we could get this feature re-implemented, then I will be able to upgrade (since I just reverted back to v3.1 to retain this feature)!

Thanks everyone!
Collin

Below is a screenshot from v3.1 of the feature to which I am referring!

https://cloud.githubusercontent.com/assets/16417247/11981995/71a87d76-a95c-11e5-8844-e58d9ba68b9d.png

**Comment by liversedge** [comment] 2015-12-23 19:05
This is a regression bug and needs to be fixed.
It is not by design.

**Comment by 3dflyer87** [comment] 2015-12-23 19:09
Sounds good, thanks liversedge!

**Comment by amtriathlon** [comment] 2022-09-30 13:28
I cannot reproduce this issue in current master, it seems to fixed in v3.6

**Closed by amtriathlon** 2022-09-30 13:28 UTC
Labels: P2, Fixed already
